
export const db_data = {
  users: [] as any[],
  listings: [
    { id: 'alger-1', ownerId: 'admin', title: 'Garage Privé - Rocade Sud (Ben Aknoun)', description: 'Garage sécurisé à proximité immédiate de la Rocade Sud. Idéal pour éviter les bouchons.', address: 'Ben Aknoun, Alger', location: { lat: 36.7525, lng: 3.0185 }, type: 'garage', pricePerHour: 80, pricePerDay: 600, pricePerWeek: 3500, pricePerMonth: 12000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1397038664/fr/photo/voitures-gar%C3%A9es-dans-un-garage-%C3%A0-plusieurs-%C3%A9tages.jpg?s=612x612&w=0&k=20&c=m2ORn2YE5KOcKvqmck8iBDcxFVJEYk71S26Fx5kJ9zI='], features: ['Accès Rapide', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-2', ownerId: 'admin', title: 'Parking Privé - Autoroute de l\'Est (Bab Ezzouar)', description: 'Parking sécurisé dans une résidence clôturée, juste à côté de l\'autoroute.', address: 'Bab Ezzouar, Alger', location: { lat: 36.7265, lng: 3.1835 }, type: 'private_spot', pricePerHour: 60, pricePerDay: 450, pricePerWeek: 2500, pricePerMonth: 8000, isNegotiable: false, images: ['https://media.istockphoto.com/id/532186572/fr/photo/les-v%C3%A9hicules-dans-le-parc-de-stationnement-en-ligne.jpg?s=612x612&w=0&k=20&c=RNTuWKjX596RCWKIR7kRbWHqDW6cpbhS9D3bXF3MCS8='], features: ['Résidence Fermée', 'Gardien'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-sofia', ownerId: 'admin', title: 'Parking Sofia', description: 'Situé en plein centre-ville, accès facile mais parfois saturé.', address: 'Accès Parking, Alger Centre, 16000', location: { lat: 36.77198, lng: 3.06025 }, type: 'private_spot', pricePerHour: 100, pricePerDay: 800, pricePerWeek: 4500, pricePerMonth: 15000, isNegotiable: false, images: ['https://aeroportalger.dz/assets/images/header/parking_to.jpg'], features: ['Centre-ville', 'Surveillé'], isAvailable: true, createdAt: Date.now() },
    { id: 'oran-1', ownerId: 'admin', title: 'Parking Privé - 2ème Rocade (Bir El Djir)', description: 'Emplacement stratégique sur la 2ème rocade d\'Oran.', address: 'Bir El Djir, Oran', location: { lat: 35.7280, lng: -0.5620 }, type: 'private_spot', pricePerHour: 70, pricePerDay: 500, pricePerWeek: 3000, pricePerMonth: 10000, isNegotiable: true, images: ['https://media.istockphoto.com/id/2178414859/photo/aerial-view-of-sparse-parking-lot-with-few-cars.jpg?s=612x612&w=0&k=20&c=FUAd8cXR_rwpuXjFZRqAMuA0YdEjP04fcuFZHFMQ-Go='], features: ['Accès Autoroute', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'const-1', ownerId: 'admin', title: 'Parking Privé - Route de Batna (Zouaghi)', description: 'Proche de l\'aéroport. Sécurisé.', address: 'Zouaghi Slimane, Constantine', location: { lat: 36.2980, lng: 6.6220 }, type: 'private_spot', pricePerHour: 60, pricePerDay: 450, pricePerWeek: 2500, pricePerMonth: 8000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1397038664/fr/photo/voitures-gar%C3%A9es-dans-un-garage-%C3%A0-plusieurs-%C3%A9tages.jpg?s=612x612&w=0&k=20&c=m2ORn2YE5KOcKvqmck8iBDcxFVJEYk71S26Fx5kJ9zI='], features: ['Proche Aéroport', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'bba-1', ownerId: 'admin', title: 'Parking Privé - RN5 (Entrée Est)', description: 'Accès direct au centre-ville.', address: 'RN5, Bordj Bou Arreridj', location: { lat: 36.0755, lng: 4.7750 }, type: 'private_spot', pricePerHour: 50, pricePerDay: 350, pricePerWeek: 2000, pricePerMonth: 7000, isNegotiable: true, images: ['https://images.unsplash.com/photo-1526626607369-f89fe1ed77a9?q=80&w=1170&auto=format&fit=crop'], features: ['Central', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'setif-1', ownerId: 'admin', title: 'Parking Privé - Boulevard de l\'ALN', description: 'En plein coeur de Sétif.', address: 'Boulevard de l\'ALN, Sétif', location: { lat: 36.1910, lng: 5.4120 }, type: 'private_spot', pricePerHour: 60, pricePerDay: 450, pricePerWeek: 2500, pricePerMonth: 8000, isNegotiable: true, images: ['https://media.istockphoto.com/id/2201862537/photo/cars-lined-up-in-a-parking-lot.jpg?s=612x612&w=0&k=20&c=M9CEct4EvUmensRC6vkyXYxyT-iQmHZkELCiJ0EpYiw='], features: ['Centre-Ville', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'toll-alg-boum', ownerId: 'admin', title: 'Péage Alger - Boumerdes', description: 'Pass pour le tronçon Alger / Boumerdes via l\'A2.', address: 'Barrière de Khemis El Khechna', location: { lat: 36.6550, lng: 3.3250 }, type: 'toll_badge', pricePerHour: 20, pricePerDay: 20, pricePerWeek: 20, pricePerMonth: 20, isNegotiable: false, images: ['https://images.unsplash.com/photo-1545179212-073c880ec19d?q=80&w=1170&auto=format&fit=crop'], features: ['A2 Est', 'Voie Rapide'], isAvailable: true, createdAt: Date.now(), route: { start: { lat: 36.7525, lng: 3.0412 }, end: { lat: 36.7620, lng: 3.4750 } } },
  ],
  bookings: [] as any[],
  messages: [] as any[],
};
