import express from 'express';
import cors from 'cors';
import path from 'path';
import { fileURLToPath } from 'url';
import { createServer as createViteServer } from 'vite';
import { v4 as uuidv4 } from 'uuid';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const JWT_SECRET = process.env.JWT_SECRET || 'parkhome-secret-key';

// In-memory "database"
const db = {
  users: [] as any[],
  listings: [
    // --- ALGER (Axes: Rocade Sud, Autoroute de l'Est, Boulevard des Martyrs) ---
    { id: 'alger-1', ownerId: 'admin', title: 'Garage Privé - Rocade Sud (Ben Aknoun)', description: 'Garage sécurisé à proximité immédiate de la Rocade Sud. Idéal pour éviter les bouchons. Entre de bonnes mains.', address: 'Ben Aknoun, Alger (Près Rocade Sud)', location: { lat: 36.7525, lng: 3.0185 }, type: 'garage', pricePerHour: 80, pricePerDay: 600, pricePerWeek: 3500, pricePerMonth: 12000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1397038664/fr/photo/voitures-gar%C3%A9es-dans-un-garage-%C3%A0-plusieurs-%C3%A9tages.jpg?s=612x612&w=0&k=20&c=m2ORn2YE5KOcKvqmck8iBDcxFVJEYk71S26Fx5kJ9zI='], features: ['Accès Rapide', 'Vidéosurveillance', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-2', ownerId: 'admin', title: 'Parking Privé - Autoroute de l\'Est (Bab Ezzouar)', description: 'Parking sécurisé dans une résidence clôturée, juste à côté de l\'autoroute. Surveillance 24/7.', address: 'Bab Ezzouar, Alger (Axe Autoroute Est)', location: { lat: 36.7265, lng: 3.1835 }, type: 'private_spot', pricePerHour: 60, pricePerDay: 450, pricePerWeek: 2500, pricePerMonth: 8000, isNegotiable: false, images: ['https://media.istockphoto.com/id/532186572/fr/photo/les-v%C3%A9hicules-dans-le-parc-de-stationnement-en-ligne.jpg?s=612x612&w=0&k=20&c=RNTuWKjX596RCWKIR7kRbWHqDW6cpbhS9D3bXF3MCS8='], features: ['Résidence Fermée', 'Proche Aéroport', 'Gardien'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-3', ownerId: 'admin', title: 'Parking en Jardin Sécurisé - Boulevard des Martyrs', description: 'Parking privé dans un jardin clos et sécurisé sur l\'axe principal des Martyrs. Entre de bonnes mains.', address: 'Boulevard des Martyrs, Alger Centre', location: { lat: 36.7580, lng: 3.0450 }, type: 'garden_spot', pricePerHour: 100, pricePerDay: 800, pricePerWeek: 5000, pricePerMonth: 18000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1869208128/photo/a-row-of-parked-cars.jpg?s=612x612&w=0&k=20&c=6tEIF93R8KIkaCNuM0P2baAiPavFCmm6FtQ9-sED-rU='], features: ['Jardin Clos', 'Centre-Ville', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-4', ownerId: 'admin', title: 'Garage Sécurisé - Hydra', description: 'Garage individuel fermé dans le quartier de Hydra. Très sécurisé, idéal pour longue durée.', address: 'Hydra, Alger', location: { lat: 36.7420, lng: 3.0350 }, type: 'garage', pricePerHour: 90, pricePerDay: 700, pricePerWeek: 4000, pricePerMonth: 15000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1350571198/photo/car-parked-at-parking-lot-of-the-airport-for-rental-aerial-view-of-car-parking-lot-of-the.jpg?s=612x612&w=0&k=20&c=Ty6ynDickWwoQ9scBUqXaoTdij0hQOVlkOftwNEfOKA='], features: ['Fermé', 'Quartier Chic', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-5', ownerId: 'admin', title: 'Parking Privé - Kouba', description: 'Parking dans une cour privée sécurisée à Kouba. Entre de bonnes mains.', address: 'Kouba, Alger', location: { lat: 36.7250, lng: 3.0850 }, type: 'private_spot', pricePerHour: 50, pricePerDay: 400, pricePerWeek: 2200, pricePerMonth: 7500, isNegotiable: true, images: ['https://media.istockphoto.com/id/2222870577/photo/aerial-view-of-parking-lot-with-single-car.jpg?s=612x612&w=0&k=20&c=xpN9-x3VQSEO-al9LOwd52E3vEw6dV1FZQvr9Lrj4IA='], features: ['Cour Privée', 'Calme', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-6', ownerId: 'admin', title: 'Jardin Clos - El Biar', description: 'Emplacement sécurisé dans un grand jardin à El Biar. Très discret.', address: 'El Biar, Alger', location: { lat: 36.7650, lng: 3.0280 }, type: 'garden_spot', pricePerHour: 70, pricePerDay: 550, pricePerWeek: 3000, pricePerMonth: 10000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1869208128/photo/a-row-of-parked-cars.jpg?s=612x612&w=0&k=20&c=6tEIF93R8KIkaCNuM0P2baAiPavFCmm6FtQ9-sED-rU='], features: ['Jardin', 'Discret', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-7', ownerId: 'admin', title: 'Box Privé - Cheraga', description: 'Box de stockage et parking sécurisé à Cheraga. Accès 24/7.', address: 'Cheraga, Alger', location: { lat: 36.7680, lng: 2.9550 }, type: 'garage', pricePerHour: 85, pricePerDay: 650, pricePerWeek: 3800, pricePerMonth: 13000, isNegotiable: false, images: ['https://media.istockphoto.com/id/1350571198/photo/car-parked-at-parking-lot-of-the-airport-for-rental-aerial-view-of-car-parking-lot-of-the.jpg?s=612x612&w=0&k=20&c=Ty6ynDickWwoQ9scBUqXaoTdij0hQOVlkOftwNEfOKA='], features: ['Box', 'Accès 24/7', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-8', ownerId: 'admin', title: 'Parking Résidentiel - Dely Ibrahim', description: 'Parking dans une résidence gardée à Dely Ibrahim.', address: 'Dely Ibrahim, Alger', location: { lat: 36.7520, lng: 2.9850 }, type: 'private_spot', pricePerHour: 55, pricePerDay: 420, pricePerWeek: 2400, pricePerMonth: 8500, isNegotiable: true, images: ['https://media.istockphoto.com/id/2222870577/photo/aerial-view-of-parking-lot-with-single-car.jpg?s=612x612&w=0&k=20&c=xpN9-x3VQSEO-al9LOwd52E3vEw6dV1FZQvr9Lrj4IA='], features: ['Résidence Gardée', 'Eclairé', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },

    // --- NEW ALGER CENTRE LISTINGS ---
    { id: 'alger-sofia', ownerId: 'admin', title: 'Parking Sofia', description: 'Situé en plein centre-ville, accès facile mais parfois saturé. Idéal pour vos rendez-vous en centre-ville.', address: 'Accès Parking, Alger Centre, 16000', location: { lat: 36.77198, lng: 3.06025 }, type: 'private_spot', pricePerHour: 100, pricePerDay: 800, pricePerWeek: 4500, pricePerMonth: 15000, isNegotiable: false, images: ['https://aeroportalger.dz/assets/images/header/parking_to.jpg'], features: ['Centre-ville', 'Accès Facile', 'Surveillé'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-bouneta', ownerId: 'admin', title: 'Parking Bouneta', description: 'Parking public à Rue d’Angkor, souvent utilisé par les résidents et visiteurs. Très pratique.', address: 'Rue d’Angkor, Alger Centre', location: { lat: 36.7750, lng: 3.0580 }, type: 'private_spot', pricePerHour: 80, pricePerDay: 600, pricePerWeek: 3500, pricePerMonth: 12000, isNegotiable: true, images: ['https://www.metalstructure.dz/wp-content/uploads/2018/02/Parking2.jpg'], features: ['Résidentiel', 'Visiteurs', 'Quartier Calme'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-port', ownerId: 'admin', title: 'Parking Port d’Alger', description: 'Pratique pour les visiteurs venant en voiture depuis la côte est. Situé dans la zone du Port.', address: 'Zone du Port, Alger Centre', location: { lat: 36.7650, lng: 3.0650 }, type: 'private_spot', pricePerHour: 70, pricePerDay: 500, pricePerWeek: 3000, pricePerMonth: 10000, isNegotiable: false, images: ['https://media.istockphoto.com/id/1869208128/photo/a-row-of-parked-cars.jpg?s=612x612&w=0&k=20&c=6tEIF93R8KIkaCNuM0P2baAiPavFCmm6FtQ9-sED-rU='], features: ['Zone Portuaire', 'Accès Côte Est', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-didouche', ownerId: 'admin', title: 'Parking Didouche Mourad', description: 'Proche des commerces et du centre administratif. Emplacement stratégique sur la Rue Didouche Mourad.', address: 'Rue Didouche Mourad, Sidi M’Hamed', location: { lat: 36.7620, lng: 3.0480 }, type: 'private_spot', pricePerHour: 120, pricePerDay: 900, pricePerWeek: 5000, pricePerMonth: 18000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1350571198/photo/car-parked-at-parking-lot-of-the-airport-for-rental-aerial-view-of-car-parking-lot-of-the.jpg?s=612x612&w=0&k=20&c=Ty6ynDickWwoQ9scBUqXaoTdij0hQOVlkOftwNEfOKA='], features: ['Commerces', 'Administratif', 'Central'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-smart', ownerId: 'admin', title: 'Parking Intelligent 1er Mai', description: 'Parking moderne et surveillé à Rue Hassiba Ben Bouali. Technologie de pointe.', address: 'Rue Hassiba Ben Bouali, Sidi M’Hamed', location: { lat: 36.7520, lng: 3.0550 }, type: 'garden_spot', pricePerHour: 150, pricePerDay: 1000, pricePerWeek: 6000, pricePerMonth: 20000, isNegotiable: false, images: ['https://media.istockphoto.com/id/2222870577/photo/aerial-view-of-parking-lot-with-single-car.jpg?s=612x612&w=0&k=20&c=xpN9-x3VQSEO-al9LOwd52E3vEw6dV1FZQvr9Lrj4IA='], features: ['Moderne', 'Intelligent', 'Haute Sécurité'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-hamma', ownerId: 'admin', title: 'Parking Jardin d’Essai du Hamma', description: 'Idéal pour visiter le Jardin d’Essai ou le musée des Beaux-Arts. Très spacieux.', address: '170 Rue Hassiba Ben Bouali, Belouizdad', location: { lat: 36.7480, lng: 3.0720 }, type: 'private_spot', pricePerHour: 60, pricePerDay: 400, pricePerWeek: 2200, pricePerMonth: 8000, isNegotiable: false, images: ['https://media.istockphoto.com/id/532186572/fr/photo/les-v%C3%A9hicules-dans-le-parc-de-stationnement-en-ligne.jpg?s=612x612&w=0&k=20&c=RNTuWKjX596RCWKIR7kRbWHqDW6cpbhS9D3bXF3MCS8='], features: ['Jardin d\'Essai', 'Belouizdad', 'Spacieux'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-omar', ownerId: 'admin', title: 'Parking Omar 24/24', description: 'Pratique pour le stationnement longue durée, ouvert 24h/24 à Dar Donald.', address: 'Dar Donald, Belouizdad', location: { lat: 36.7450, lng: 3.0780 }, type: 'garage', pricePerHour: 50, pricePerDay: 350, pricePerWeek: 2000, pricePerMonth: 7000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1397038664/fr/photo/voitures-gar%C3%A9es-dans-un-garage-%C3%A0-plusieurs-%C3%A9tages.jpg?s=612x612&w=0&k=20&c=m2ORn2YE5KOcKvqmck8iBDcxFVJEYk71S26Fx5kJ9zI='], features: ['24h/24', 'Longue Durée', 'Belouizdad'], isAvailable: true, createdAt: Date.now() },

    // --- ORAN (Axes: 2ème Rocade, Boulevard Front de Mer, Route de Tlemcen) ---
    { id: 'oran-1', ownerId: 'admin', title: 'Parking Privé - 2ème Rocade (Bir El Djir)', description: 'Emplacement stratégique sur la 2ème rocade d\'Oran. Accès facile et sécurisé.', address: 'Bir El Djir, Oran (2ème Rocade)', location: { lat: 35.7280, lng: -0.5620 }, type: 'private_spot', pricePerHour: 70, pricePerDay: 500, pricePerWeek: 3000, pricePerMonth: 10000, isNegotiable: true, images: ['https://media.istockphoto.com/id/2178414859/photo/aerial-view-of-sparse-parking-lot-with-few-cars.jpg?s=612x612&w=0&k=20&c=FUAd8cXR_rwpuXjFZRqAMuA0YdEjP04fcuFZHFMQ-Go='], features: ['Accès Autoroute', 'Eclairé', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'oran-2', ownerId: 'admin', title: 'Garage - Boulevard Front de Mer', description: 'Garage privé situé sur le célèbre Front de Mer d\'Oran. Très sécurisé.', address: 'Front de Mer, Oran', location: { lat: 35.7085, lng: -0.6350 }, type: 'garage', pricePerHour: 90, pricePerDay: 700, pricePerWeek: 4000, pricePerMonth: 14000, isNegotiable: false, images: ['https://media.istockphoto.com/id/2201862537/photo/cars-lined-up-in-a-parking-lot.jpg?s=612x612&w=0&k=20&c=M9CEct4EvUmensRC6vkyXYxyT-iQmHZkELCiJ0EpYiw='], features: ['Vue Mer', 'Sécurisé', 'Fermé'], isAvailable: true, createdAt: Date.now() },
    { id: 'oran-3', ownerId: 'admin', title: 'Parking en Jardin - Route de Tlemcen', description: 'Parking calme dans un jardin privé sécurisé sur l\'axe menant à Tlemcen.', address: 'Route de Tlemcen, Oran Ouest', location: { lat: 35.6850, lng: -0.6850 }, type: 'garden_spot', pricePerHour: 50, pricePerDay: 400, pricePerWeek: 2000, pricePerMonth: 7000, isNegotiable: true, images: ['https://images.unsplash.com/photo-1506521781263-d8422e82f27a?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'], features: ['Calme', 'Jardin Sécurisé', 'Entre de bonnes mains'], isAvailable: true, createdAt: Date.now() },
    { id: 'oran-4', ownerId: 'admin', title: 'Garage Sécurisé - Akid Lotfi', description: 'Garage privé dans le quartier animé d\'Akid Lotfi. Sécurisé 24/7.', address: 'Akid Lotfi, Oran', location: { lat: 35.7150, lng: -0.5850 }, type: 'garage', pricePerHour: 80, pricePerDay: 600, pricePerWeek: 3500, pricePerMonth: 12000, isNegotiable: true, images: ['https://images.unsplash.com/photo-1526626607369-f89fe1ed77a9?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'], features: ['Fermé', 'Quartier Animé', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'oran-5', ownerId: 'admin', title: 'Parking Privé - Canastel', description: 'Parking sécurisé dans le quartier résidentiel de Canastel.', address: 'Canastel, Oran', location: { lat: 35.7350, lng: -0.5750 }, type: 'private_spot', pricePerHour: 60, pricePerDay: 450, pricePerWeek: 2500, pricePerMonth: 9000, isNegotiable: true, images: ['https://images.unsplash.com/photo-1612917231506-a0825d1bc76d?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'], features: ['Résidentiel', 'Calme', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'oran-6', ownerId: 'admin', title: 'Jardin Clos - Gambetta', description: 'Emplacement dans un jardin privé sécurisé à Gambetta. Entre de bonnes mains.', address: 'Gambetta, Oran', location: { lat: 35.7120, lng: -0.6150 }, type: 'garden_spot', pricePerHour: 55, pricePerDay: 400, pricePerWeek: 2200, pricePerMonth: 8000, isNegotiable: true, images: ['https://media.istockphoto.com/id/2178414859/photo/aerial-view-of-sparse-parking-lot-with-few-cars.jpg?s=612x612&w=0&k=20&c=FUAd8cXR_rwpuXjFZRqAMuA0YdEjP04fcuFZHFMQ-Go='], features: ['Jardin', 'Sécurisé', 'Proche Centre'], isAvailable: true, createdAt: Date.now() },
    { id: 'oran-7', ownerId: 'admin', title: 'Box Privé - Maraval', description: 'Box sécurisé pour voiture à Maraval. Idéal pour stationnement longue durée.', address: 'Maraval, Oran', location: { lat: 35.6880, lng: -0.6450 }, type: 'garage', pricePerHour: 75, pricePerDay: 550, pricePerWeek: 3200, pricePerMonth: 11000, isNegotiable: false, images: ['https://media.istockphoto.com/id/2201862537/photo/cars-lined-up-in-a-parking-lot.jpg?s=612x612&w=0&k=20&c=M9CEct4EvUmensRC6vkyXYxyT-iQmHZkELCiJ0EpYiw='], features: ['Box', 'Sécurisé', 'Longue Durée'], isAvailable: true, createdAt: Date.now() },
    { id: 'oran-8', ownerId: 'admin', title: 'Parking Résidentiel - Es Senia', description: 'Parking sécurisé à Es Senia, proche de l\'université.', address: 'Es Senia, Oran', location: { lat: 35.6550, lng: -0.6250 }, type: 'private_spot', pricePerHour: 45, pricePerDay: 350, pricePerWeek: 1800, pricePerMonth: 6500, isNegotiable: true, images: ['https://images.unsplash.com/photo-1506521781263-d8422e82f27a?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'], features: ['Proche Université', 'Sécurisé', 'Eclairé'], isAvailable: true, createdAt: Date.now() },

    // --- CONSTANTINE (Axes: Route de Batna, Route de Skikda, Centre-Ville) ---
    { id: 'const-1', ownerId: 'admin', title: 'Parking Privé - Route de Batna (Zouaghi)', description: 'Proche de l\'axe principal vers Batna et de l\'aéroport. Sécurisé.', address: 'Zouaghi Slimane, Constantine', location: { lat: 36.2980, lng: 6.6220 }, type: 'private_spot', pricePerHour: 60, pricePerDay: 450, pricePerWeek: 2500, pricePerMonth: 8000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1397038664/fr/photo/voitures-gar%C3%A9es-dans-un-garage-%C3%A0-plusieurs-%C3%A9tages.jpg?s=612x612&w=0&k=20&c=m2ORn2YE5KOcKvqmck8iBDcxFVJEYk71S26Fx5kJ9zI='], features: ['Proche Aéroport', 'Axe Principal', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'const-2', ownerId: 'admin', title: 'Garage Sécurisé - Route de Skikda', description: 'Garage fermé sur l\'axe Constantine-Skikda. Entre de bonnes mains.', address: 'Route de Skikda, Constantine Nord', location: { lat: 36.3850, lng: 6.6550 }, type: 'garage', pricePerHour: 80, pricePerDay: 600, pricePerWeek: 3500, pricePerMonth: 12000, isNegotiable: false, images: ['https://media.istockphoto.com/id/532186572/fr/photo/les-v%C3%A9hicules-dans-le-parc-de-stationnement-en-ligne.jpg?s=612x612&w=0&k=20&c=RNTuWKjX596RCWKIR7kRbWHqDW6cpbhS9D3bXF3MCS8='], features: ['Fermé', 'Vidéosurveillance', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'const-3', ownerId: 'admin', title: 'Parking en Jardin - Centre (Pont Sidi M\'Cid)', description: 'Parking privé dans un jardin à deux pas du célèbre pont suspendu. Très sécurisé.', address: 'Quartier du Pont, Constantine', location: { lat: 36.3680, lng: 6.6150 }, type: 'garden_spot', pricePerHour: 70, pricePerDay: 500, pricePerWeek: 3000, pricePerMonth: 10000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1869208128/photo/a-row-of-parked-cars.jpg?s=612x612&w=0&k=20&c=6tEIF93R8KIkaCNuM0P2baAiPavFCmm6FtQ9-sED-rU='], features: ['Vue Panoramique', 'Central', 'Jardin Clos'], isAvailable: true, createdAt: Date.now() },
    { id: 'const-4', ownerId: 'admin', title: 'Garage Privé - Nouvelle Ville (Ali Mendjeli)', description: 'Garage sécurisé dans la nouvelle ville d\'Ali Mendjeli. Accès facile.', address: 'Ali Mendjeli, Constantine', location: { lat: 36.2450, lng: 6.5850 }, type: 'garage', pricePerHour: 75, pricePerDay: 550, pricePerWeek: 3200, pricePerMonth: 11000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1350571198/photo/car-parked-at-parking-lot-of-the-airport-for-rental-aerial-view-of-car-parking-lot-of-the.jpg?s=612x612&w=0&k=20&c=Ty6ynDickWwoQ9scBUqXaoTdij0hQOVlkOftwNEfOKA='], features: ['Nouvelle Ville', 'Sécurisé', 'Fermé'], isAvailable: true, createdAt: Date.now() },
    { id: 'const-5', ownerId: 'admin', title: 'Parking Privé - Bellevue', description: 'Parking sécurisé dans le quartier calme de Bellevue.', address: 'Bellevue, Constantine', location: { lat: 36.3550, lng: 6.6050 }, type: 'private_spot', pricePerHour: 55, pricePerDay: 400, pricePerWeek: 2200, pricePerMonth: 8000, isNegotiable: true, images: ['https://media.istockphoto.com/id/2222870577/photo/aerial-view-of-parking-lot-with-single-car.jpg?s=612x612&w=0&k=20&c=xpN9-x3VQSEO-al9LOwd52E3vEw6dV1FZQvr9Lrj4IA='], features: ['Quartier Calme', 'Sécurisé', 'Eclairé'], isAvailable: true, createdAt: Date.now() },
    { id: 'const-6', ownerId: 'admin', title: 'Jardin Clos - Sidi Mabrouk', description: 'Emplacement sécurisé dans un jardin privé à Sidi Mabrouk. Entre de bonnes mains.', address: 'Sidi Mabrouk, Constantine', location: { lat: 36.3420, lng: 6.6350 }, type: 'garden_spot', pricePerHour: 50, pricePerDay: 350, pricePerWeek: 2000, pricePerMonth: 7000, isNegotiable: true, images: ['https://media.istockphoto.com/id/2178414859/photo/aerial-view-of-sparse-parking-lot-with-few-cars.jpg?s=612x612&w=0&k=20&c=FUAd8cXR_rwpuXjFZRqAMuA0YdEjP04fcuFZHFMQ-Go='], features: ['Jardin', 'Sécurisé', 'Discret'], isAvailable: true, createdAt: Date.now() },
    { id: 'const-7', ownerId: 'admin', title: 'Box Privé - El Khroub', description: 'Box sécurisé à El Khroub, idéal for stationnement longue durée.', address: 'El Khroub, Constantine', location: { lat: 36.2650, lng: 6.6950 }, type: 'garage', pricePerHour: 65, pricePerDay: 480, pricePerWeek: 2800, pricePerMonth: 9500, isNegotiable: false, images: ['https://media.istockphoto.com/id/2201862537/photo/cars-lined-up-in-a-parking-lot.jpg?s=612x612&w=0&k=20&c=M9CEct4EvUmensRC6vkyXYxyT-iQmHZkELCiJ0EpYiw='], features: ['Box', 'Sécurisé', 'Longue Durée'], isAvailable: true, createdAt: Date.now() },
    { id: 'const-8', ownerId: 'admin', title: 'Parking Résidentiel - Daksi', description: 'Parking sécurisé dans la cité Daksi. Gardiennage assuré.', address: 'Daksi, Constantine', location: { lat: 36.3580, lng: 6.6450 }, type: 'private_spot', pricePerHour: 45, pricePerDay: 350, pricePerWeek: 1800, pricePerMonth: 6000, isNegotiable: true, images: ['https://media.istockphoto.com/id/2201862537/photo/cars-lined-up-in-a-parking-lot.jpg?s=612x612&w=0&k=20&c=M9CEct4EvUmensRC6vkyXYxyT-iQmHZkELCiJ0EpYiw='], features: ['Cité Gardée', 'Sécurisé', 'Accessible'], isAvailable: true, createdAt: Date.now() },

    // --- BORDJ BOU ARRERIDJ (Axes: RN5, Autoroute Est-Ouest, Route de M\'Sila) ---
    { id: 'bba-1', ownerId: 'admin', title: 'Parking Privé - RN5 (Entrée Est)', description: 'Situé sur la route nationale 5, accès direct au centre-ville. Sécurisé.', address: 'RN5, Bordj Bou Arreridj', location: { lat: 36.0755, lng: 4.7750 }, type: 'private_spot', pricePerHour: 50, pricePerDay: 350, pricePerWeek: 2000, pricePerMonth: 7000, isNegotiable: true, images: ['https://images.unsplash.com/photo-1526626607369-f89fe1ed77a9?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'], features: ['Accès RN5', 'Spacieux', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'bba-2', ownerId: 'admin', title: 'Garage Fermé - Axe Autoroute (Sortie Ouest)', description: 'Garage sécurisé proche de l\'échangeur de l\'autoroute Est-Ouest. Entre de bonnes mains.', address: 'Sortie Ouest, BBA', location: { lat: 36.0650, lng: 4.7350 }, type: 'garage', pricePerHour: 70, pricePerDay: 500, pricePerWeek: 3000, pricePerMonth: 10000, isNegotiable: false, images: ['https://images.unsplash.com/photo-1612917231506-a0825d1bc76d?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'], features: ['Proche Autoroute', 'Sécurisé', 'Fermé'], isAvailable: true, createdAt: Date.now() },
    { id: 'bba-3', ownerId: 'admin', title: 'Parking en Jardin - Route de M\'Sila', description: 'Parking privé dans un jardin sécurisé sur l\'axe BBA-M\'Sila.', address: 'Route de M\'Sila, BBA Sud', location: { lat: 36.0550, lng: 4.7620 }, type: 'garden_spot', pricePerHour: 40, pricePerDay: 300, pricePerWeek: 1500, pricePerMonth: 5000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1397038664/fr/photo/voitures-gar%C3%A9es-dans-un-garage-%C3%A0-plusieurs-%C3%A9tages.jpg?s=612x612&w=0&k=20&c=m2ORn2YE5KOcKvqmck8iBDcxFVJEYk71S26Fx5kJ9zI='], features: ['Axe Sud', 'Calme', 'Jardin Clos'], isAvailable: true, createdAt: Date.now() },
    { id: 'bba-4', ownerId: 'admin', title: 'Garage Privé - Quartier Administratif', description: 'Garage sécurisé au centre de BBA, proche des administrations.', address: 'Centre-Ville, BBA', location: { lat: 36.0720, lng: 4.7650 }, type: 'garage', pricePerHour: 60, pricePerDay: 450, pricePerWeek: 2500, pricePerMonth: 8000, isNegotiable: true, images: ['https://media.istockphoto.com/id/532186572/fr/photo/les-v%C3%A9hicules-dans-le-parc-de-stationnement-en-ligne.jpg?s=612x612&w=0&k=20&c=RNTuWKjX596RCWKIR7kRbWHqDW6cpbhS9D3bXF3MCS8='], features: ['Central', 'Sécurisé', 'Fermé'], isAvailable: true, createdAt: Date.now() },
    { id: 'bba-5', ownerId: 'admin', title: 'Parking Privé - Cité 500 Logements', description: 'Parking sécurisé dans une cité calme à BBA.', address: 'Cité 500 Logements, BBA', location: { lat: 36.0820, lng: 4.7550 }, type: 'private_spot', pricePerHour: 35, pricePerDay: 250, pricePerWeek: 1500, pricePerMonth: 5000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1869208128/photo/a-row-of-parked-cars.jpg?s=612x612&w=0&k=20&c=6tEIF93R8KIkaCNuM0P2baAiPavFCmm6FtQ9-sED-rU='], features: ['Calme', 'Sécurisé', 'Accessible'], isAvailable: true, createdAt: Date.now() },
    { id: 'bba-6', ownerId: 'admin', title: 'Jardin Clos - Route de Sétif', description: 'Emplacement sécurisé dans un jardin privé on the axe BBA-Sétif.', address: 'Route de Sétif, BBA', location: { lat: 36.0780, lng: 4.7850 }, type: 'garden_spot', pricePerHour: 45, pricePerDay: 300, pricePerWeek: 1800, pricePerMonth: 6000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1350571198/photo/car-parked-at-parking-lot-of-the-airport-for-rental-aerial-view-of-car-parking-lot-of-the.jpg?s=612x612&w=0&k=20&c=Ty6ynDickWwoQ9scBUqXaoTdij0hQOVlkOftwNEfOKA='], features: ['Jardin', 'Sécurisé', 'Axe Principal'], isAvailable: true, createdAt: Date.now() },
    { id: 'bba-7', ownerId: 'admin', title: 'Box Privé - Zone Industrielle', description: 'Box sécurisé proche de la zone industrielle de BBA.', address: 'Zone Industrielle, BBA', location: { lat: 36.0450, lng: 4.7450 }, type: 'garage', pricePerHour: 55, pricePerDay: 400, pricePerWeek: 2200, pricePerMonth: 7500, isNegotiable: false, images: ['https://media.istockphoto.com/id/2222870577/photo/aerial-view-of-parking-lot-with-single-car.jpg?s=612x612&w=0&k=20&c=xpN9-x3VQSEO-al9LOwd52E3vEw6dV1FZQvr9Lrj4IA='], features: ['Box', 'Sécurisé', 'Zone Calme'], isAvailable: true, createdAt: Date.now() },
    { id: 'bba-8', ownerId: 'admin', title: 'Parking Résidentiel - Quartier Nord', description: 'Parking sécurisé dans le quartier Nord de BBA.', address: 'Quartier Nord, BBA', location: { lat: 36.0950, lng: 4.7680 }, type: 'private_spot', pricePerHour: 30, pricePerDay: 200, pricePerWeek: 1200, pricePerMonth: 4000, isNegotiable: true, images: ['https://media.istockphoto.com/id/2178414859/photo/aerial-view-of-sparse-parking-lot-with-few-cars.jpg?s=612x612&w=0&k=20&c=FUAd8cXR_rwpuXjFZRqAMuA0YdEjP04fcuFZHFMQ-Go='], features: ['Résidentiel', 'Sécurisé', 'Economique'], isAvailable: true, createdAt: Date.now() },

    // --- SETIF (Axes: Boulevard de l'ALN, Route de Constantine, Axe Sud) ---
    { id: 'setif-1', ownerId: 'admin', title: 'Parking Privé - Boulevard de l\'ALN', description: 'En plein coeur de Sétif, sur l\'axe principal de l\'ALN. Sécurisé.', address: 'Boulevard de l\'ALN, Sétif', location: { lat: 36.1910, lng: 5.4120 }, type: 'private_spot', pricePerHour: 60, pricePerDay: 450, pricePerWeek: 2500, pricePerMonth: 8000, isNegotiable: true, images: ['https://media.istockphoto.com/id/2201862537/photo/cars-lined-up-in-a-parking-lot.jpg?s=612x612&w=0&k=20&c=M9CEct4EvUmensRC6vkyXYxyT-iQmHZkELCiJ0EpYiw='], features: ['Centre-Ville', 'Eclairé', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'setif-2', ownerId: 'admin', title: 'Garage - Route de Constantine', description: 'Garage sécurisé sur l\'axe vers Constantine. Entre de bonnes mains.', address: 'Route de Constantine, Sétif Est', location: { lat: 36.1980, lng: 5.4450 }, type: 'garage', pricePerHour: 80, pricePerDay: 600, pricePerWeek: 3500, pricePerMonth: 12000, isNegotiable: false, images: ['https://images.unsplash.com/photo-1506521781263-d8422e82f27a?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'], features: ['Accès Rapide', 'Fermé', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'setif-3', ownerId: 'admin', title: 'Parking en Jardin - Axe Sud (El Hidhab)', description: 'Parking dans un jardin privé sécurisé sur l\'axe Sud. Entre de bonnes mains.', address: 'El Hidhab, Sétif', location: { lat: 36.2150, lng: 5.4320 }, type: 'garden_spot', pricePerHour: 50, pricePerDay: 350, pricePerWeek: 2000, pricePerMonth: 7000, isNegotiable: true, images: ['https://images.unsplash.com/photo-1526626607369-f89fe1ed77a9?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'], features: ['Résidence', 'Calme', 'Jardin Clos'], isAvailable: true, createdAt: Date.now() },
    { id: 'setif-4', ownerId: 'admin', title: 'Garage Privé - Quartier des Tours', description: 'Garage sécurisé dans le quartier des tours à Sétif. Très central.', address: 'Quartier des Tours, Sétif', location: { lat: 36.1850, lng: 5.4150 }, type: 'garage', pricePerHour: 85, pricePerDay: 650, pricePerWeek: 3800, pricePerMonth: 13000, isNegotiable: true, images: ['https://images.unsplash.com/photo-1612917231506-a0825d1bc76d?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'], features: ['Central', 'Sécurisé', 'Fermé'], isAvailable: true, createdAt: Date.now() },
    { id: 'setif-5', ownerId: 'admin', title: 'Parking Privé - Cité 1000 Logements', description: 'Parking sécurisé dans une cité résidentielle à Sétif.', address: 'Cité 1000 Logements, Sétif', location: { lat: 36.2050, lng: 5.4250 }, type: 'private_spot', pricePerHour: 45, pricePerDay: 350, pricePerWeek: 2000, pricePerMonth: 7000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1397038664/fr/photo/voitures-gar%C3%A9es-dans-un-garage-%C3%A0-plusieurs-%C3%A9tages.jpg?s=612x612&w=0&k=20&c=m2ORn2YE5KOcKvqmck8iBDcxFVJEYk71S26Fx5kJ9zI='], features: ['Résidentiel', 'Sécurisé', 'Accessible'], isAvailable: true, createdAt: Date.now() },
    { id: 'setif-6', ownerId: 'admin', title: 'Jardin Clos - Route de Bejaia', description: 'Emplacement sécurisé dans un jardin privé on the axe Sétif-Bejaia.', address: 'Route de Bejaia, Sétif', location: { lat: 36.2250, lng: 5.3950 }, type: 'garden_spot', pricePerHour: 55, pricePerDay: 400, pricePerWeek: 2200, pricePerMonth: 8000, isNegotiable: true, images: ['https://media.istockphoto.com/id/532186572/fr/photo/les-v%C3%A9hicules-dans-le-parc-de-stationnement-en-ligne.jpg?s=612x612&w=0&k=20&c=RNTuWKjX596RCWKIR7kRbWHqDW6cpbhS9D3bXF3MCS8='], features: ['Jardin', 'Sécurisé', 'Axe Principal'], isAvailable: true, createdAt: Date.now() },
    { id: 'setif-7', ownerId: 'admin', title: 'Box Privé - Zone Industrielle Sétif', description: 'Box sécurisé proche de la zone industrielle de Sétif.', address: 'Zone Industrielle, Sétif', location: { lat: 36.1650, lng: 5.4550 }, type: 'garage', pricePerHour: 70, pricePerDay: 500, pricePerWeek: 3000, pricePerMonth: 10000, isNegotiable: false, images: ['https://media.istockphoto.com/id/1869208128/photo/a-row-of-parked-cars.jpg?s=612x612&w=0&k=20&c=6tEIF93R8KIkaCNuM0P2baAiPavFCmm6FtQ9-sED-rU='], features: ['Box', 'Sécurisé', 'Zone Calme'], isAvailable: true, createdAt: Date.now() },
    { id: 'setif-8', ownerId: 'admin', title: 'Parking Résidentiel - Quartier Nord Sétif', description: 'Parking sécurisé dans le quartier Nord de Sétif.', address: 'Quartier Nord, Sétif', location: { lat: 36.2350, lng: 5.4180 }, type: 'private_spot', pricePerHour: 40, pricePerDay: 300, pricePerWeek: 1800, pricePerMonth: 6000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1350571198/photo/car-parked-at-parking-lot-of-the-airport-for-rental-aerial-view-of-car-parking-lot-of-the.jpg?s=612x612&w=0&k=20&c=Ty6ynDickWwoQ9scBUqXaoTdij0hQOVlkOftwNEfOKA='], features: ['Résidentiel', 'Sécurisé', 'Economique'], isAvailable: true, createdAt: Date.now() },

    // --- DJELFA (Axes: RN1 Nord, Route de Laghouat, Centre-Ville) ---
    { id: 'djelfa-1', ownerId: 'admin', title: 'Parking Privé - Axe RN1 (Nord)', description: 'Idéal pour les voyageurs transitant par la RN1. Sécurisé.', address: 'RN1 Nord, Djelfa', location: { lat: 34.6850, lng: 3.2650 }, type: 'private_spot', pricePerHour: 40, pricePerDay: 300, pricePerWeek: 1500, pricePerMonth: 5000, isNegotiable: true, images: ['https://media.istockphoto.com/id/2222870577/photo/aerial-view-of-parking-lot-with-single-car.jpg?s=612x612&w=0&k=20&c=xpN9-x3VQSEO-al9LOwd52E3vEw6dV1FZQvr9Lrj4IA='], features: ['Axe Transsaharien', 'Vidéosurveillance', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'djelfa-2', ownerId: 'admin', title: 'Garage - Route de Laghouat', description: 'Garage privé sécurisé on the axe Sud. Entre de bonnes mains.', address: 'Route de Laghouat, Djelfa Sud', location: { lat: 34.6550, lng: 3.2450 }, type: 'garage', pricePerHour: 60, pricePerDay: 450, pricePerWeek: 2500, pricePerMonth: 8000, isNegotiable: false, images: ['https://media.istockphoto.com/id/2178414859/photo/aerial-view-of-sparse-parking-lot-with-few-cars.jpg?s=612x612&w=0&k=20&c=FUAd8cXR_rwpuXjFZRqAMuA0YdEjP04fcuFZHFMQ-Go='], features: ['Fermé', 'Sécurisé', 'Gardien'], isAvailable: true, createdAt: Date.now() },
    { id: 'djelfa-3', ownerId: 'admin', title: 'Parking en Jardin - Centre-Ville Djelfa', description: 'Parking privé dans un jardin sécurisé proche des commerces du centre.', address: 'Centre-Ville, Djelfa', location: { lat: 34.6720, lng: 3.2620 }, type: 'garden_spot', pricePerHour: 30, pricePerDay: 250, pricePerWeek: 1200, pricePerMonth: 4000, isNegotiable: true, images: ['https://media.istockphoto.com/id/2201862537/photo/cars-lined-up-in-a-parking-lot.jpg?s=612x612&w=0&k=20&c=M9CEct4EvUmensRC6vkyXYxyT-iQmHZkELCiJ0EpYiw='], features: ['Commerces', 'Accessible', 'Jardin Clos'], isAvailable: true, createdAt: Date.now() },
    { id: 'djelfa-4', ownerId: 'admin', title: 'Garage Privé - Quartier Administratif Djelfa', description: 'Garage sécurisé proche des administrations de Djelfa.', address: 'Centre, Djelfa', location: { lat: 34.6750, lng: 3.2550 }, type: 'garage', pricePerHour: 50, pricePerDay: 350, pricePerWeek: 2000, pricePerMonth: 7000, isNegotiable: true, images: ['https://images.unsplash.com/photo-1506521781263-d8422e82f27a?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'], features: ['Central', 'Sécurisé', 'Fermé'], isAvailable: true, createdAt: Date.now() },
    { id: 'djelfa-5', ownerId: 'admin', title: 'Parking Privé - Cité 100 Logements', description: 'Parking sécurisé dans une cité résidentielle à Djelfa.', address: 'Cité 100 Logements, Djelfa', location: { lat: 34.6650, lng: 3.2750 }, type: 'private_spot', pricePerHour: 35, pricePerDay: 250, pricePerWeek: 1500, pricePerMonth: 5000, isNegotiable: true, images: ['https://images.unsplash.com/photo-1526626607369-f89fe1ed77a9?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'], features: ['Résidentiel', 'Sécurisé', 'Accessible'], isAvailable: true, createdAt: Date.now() },
    { id: 'djelfa-6', ownerId: 'admin', title: 'Jardin Clos - Route de Médéa', description: 'Emplacement sécurisé dans un jardin privé on the axe Djelfa-Médéa.', address: 'Route de Médéa, Djelfa', location: { lat: 34.7050, lng: 3.2850 }, type: 'garden_spot', pricePerHour: 45, pricePerDay: 300, pricePerWeek: 1800, pricePerMonth: 6000, isNegotiable: true, images: ['https://images.unsplash.com/photo-1612917231506-a0825d1bc76d?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'], features: ['Jardin', 'Sécurisé', 'Axe Nord'], isAvailable: true, createdAt: Date.now() },
    { id: 'djelfa-7', ownerId: 'admin', title: 'Box Privé - Zone Sud Djelfa', description: 'Box sécurisé dans la zone Sud de Djelfa.', address: 'Zone Sud, Djelfa', location: { lat: 34.6350, lng: 3.2350 }, type: 'garage', pricePerHour: 40, pricePerDay: 300, pricePerWeek: 1500, pricePerMonth: 5000, isNegotiable: false, images: ['https://media.istockphoto.com/id/1397038664/fr/photo/voitures-gar%C3%A9es-dans-un-garage-%C3%A0-plusieurs-%C3%A9tages.jpg?s=612x612&w=0&k=20&c=m2ORn2YE5KOcKvqmck8iBDcxFVJEYk71S26Fx5kJ9zI='], features: ['Box', 'Sécurisé', 'Zone Calme'], isAvailable: true, createdAt: Date.now() },
    { id: 'djelfa-8', ownerId: 'admin', title: 'Parking Résidentiel - Quartier Est Djelfa', description: 'Parking sécurisé dans le quartier Est de Djelfa.', address: 'Quartier Est, Djelfa', location: { lat: 34.6820, lng: 3.2950 }, type: 'private_spot', pricePerHour: 30, pricePerDay: 200, pricePerWeek: 1200, pricePerMonth: 4000, isNegotiable: true, images: ['https://media.istockphoto.com/id/532186572/fr/photo/les-v%C3%A9hicules-dans-le-parc-de-stationnement-en-ligne.jpg?s=612x612&w=0&k=20&c=RNTuWKjX596RCWKIR7kRbWHqDW6cpbhS9D3bXF3MCS8='], features: ['Résidentiel', 'Sécurisé', 'Economique'], isAvailable: true, createdAt: Date.now() },

    // --- BEJAIA (Axes: Route des Aurès, Boulevard Krim Belkacem, Axe Ouest) ---
    { id: 'bejaia-1', ownerId: 'admin', title: 'Parking Privé - Route des Aurès', description: 'Parking sécurisé sur l\'axe principal menant au port. Entre de bonnes mains.', address: 'Route des Aurès, Bejaia', location: { lat: 36.7550, lng: 5.0650 }, type: 'private_spot', pricePerHour: 70, pricePerDay: 500, pricePerWeek: 3000, pricePerMonth: 10000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1869208128/photo/a-row-of-parked-cars.jpg?s=612x612&w=0&k=20&c=6tEIF93R8KIkaCNuM0P2baAiPavFCmm6FtQ9-sED-rU='], features: ['Proche Port', 'Axe Principal', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'bejaia-2', ownerId: 'admin', title: 'Garage - Boulevard Krim Belkacem', description: 'Garage fermé dans un quartier très fréquenté. Très sécurisé.', address: 'Boulevard Krim Belkacem, Bejaia', location: { lat: 36.7480, lng: 5.0520 }, type: 'garage', pricePerHour: 90, pricePerDay: 700, pricePerWeek: 4000, pricePerMonth: 14000, isNegotiable: false, images: ['https://media.istockphoto.com/id/1350571198/photo/car-parked-at-parking-lot-of-the-airport-for-rental-aerial-view-of-car-parking-lot-of-the.jpg?s=612x612&w=0&k=20&c=Ty6ynDickWwoQ9scBUqXaoTdij0hQOVlkOftwNEfOKA='], features: ['Fermé', 'Sécurisé', 'Vidéosurveillance'], isAvailable: true, createdAt: Date.now() },
    { id: 'bejaia-3', ownerId: 'admin', title: 'Parking en Jardin - Axe Ouest (Ihaddaden)', description: 'Parking privé dans un jardin sécurisé sur l\'axe Ouest de la ville.', address: 'Ihaddaden, Bejaia', location: { lat: 36.7420, lng: 5.0420 }, type: 'garden_spot', pricePerHour: 60, pricePerDay: 450, pricePerWeek: 2500, pricePerMonth: 8000, isNegotiable: true, images: ['https://media.istockphoto.com/id/2222870577/photo/aerial-view-of-parking-lot-with-single-car.jpg?s=612x612&w=0&k=20&c=xpN9-x3VQSEO-al9LOwd52E3vEw6dV1FZQvr9Lrj4IA='], features: ['Résidence', 'Calme', 'Jardin Clos'], isAvailable: true, createdAt: Date.now() },
    { id: 'bejaia-4', ownerId: 'admin', title: 'Garage Privé - Quartier Daouadji', description: 'Garage sécurisé dans le quartier Daouadji à Bejaia.', address: 'Quartier Daouadji, Bejaia', location: { lat: 36.7520, lng: 5.0750 }, type: 'garage', pricePerHour: 85, pricePerDay: 650, pricePerWeek: 3800, pricePerMonth: 13000, isNegotiable: true, images: ['https://media.istockphoto.com/id/2178414859/photo/aerial-view-of-sparse-parking-lot-with-few-cars.jpg?s=612x612&w=0&k=20&c=FUAd8cXR_rwpuXjFZRqAMuA0YdEjP04fcuFZHFMQ-Go='], features: ['Résidentiel', 'Sécurisé', 'Fermé'], isAvailable: true, createdAt: Date.now() },
    { id: 'bejaia-5', ownerId: 'admin', title: 'Parking Privé - Cité 600 Logements', description: 'Parking sécurisé dans une cité calme à Bejaia.', address: 'Cité 600 Logements, Bejaia', location: { lat: 36.7350, lng: 5.0450 }, type: 'private_spot', pricePerHour: 55, pricePerDay: 400, pricePerWeek: 2200, pricePerMonth: 8000, isNegotiable: true, images: ['https://media.istockphoto.com/id/2201862537/photo/cars-lined-up-in-a-parking-lot.jpg?s=612x612&w=0&k=20&c=M9CEct4EvUmensRC6vkyXYxyT-iQmHZkELCiJ0EpYiw='], features: ['Calme', 'Sécurisé', 'Accessible'], isAvailable: true, createdAt: Date.now() },
    { id: 'bejaia-6', ownerId: 'admin', title: 'Jardin Clos - Route de Jijel', description: 'Emplacement sécurisé dans un jardin privé on the axe Bejaia-Jijel.', address: 'Route de Jijel, Bejaia', location: { lat: 36.7650, lng: 5.0950 }, type: 'garden_spot', pricePerHour: 65, pricePerDay: 480, pricePerWeek: 2800, pricePerMonth: 9500, isNegotiable: true, images: ['https://images.unsplash.com/photo-1506521781263-d8422e82f27a?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'], features: ['Jardin', 'Sécurisé', 'Axe Est'], isAvailable: true, createdAt: Date.now() },
    { id: 'bejaia-7', ownerId: 'admin', title: 'Box Privé - Zone Portuaire', description: 'Box sécurisé proche de la zone portuaire de Bejaia.', address: 'Zone Portuaire, Bejaia', location: { lat: 36.7580, lng: 5.0850 }, type: 'garage', pricePerHour: 80, pricePerDay: 600, pricePerWeek: 3500, pricePerMonth: 12000, isNegotiable: false, images: ['https://images.unsplash.com/photo-1526626607369-f89fe1ed77a9?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'], features: ['Box', 'Sécurisé', 'Proche Port'], isAvailable: true, createdAt: Date.now() },
    { id: 'bejaia-8', ownerId: 'admin', title: 'Parking Résidentiel - Quartier Plateau', description: 'Parking sécurisé dans the quartier du Plateau à Bejaia.', address: 'Plateau, Bejaia', location: { lat: 36.7510, lng: 5.0580 }, type: 'private_spot', pricePerHour: 50, pricePerDay: 380, pricePerWeek: 2000, pricePerMonth: 7500, isNegotiable: true, images: ['https://images.unsplash.com/photo-1612917231506-a0825d1bc76d?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'], features: ['Résidentiel', 'Sécurisé', 'Vue Mer'], isAvailable: true, createdAt: Date.now() },

    // --- BOUMERDES (Axes: Boulevard de l'Indépendance, Route de Dellys, Axe Sud) ---
    { id: 'boumer-1', ownerId: 'admin', title: 'Parking Privé - Boulevard de l\'Indépendance', description: 'Parking central sécurisé on the axe principal de Boumerdès.', address: 'Boulevard de l\'Indépendance, Boumerdès', location: { lat: 36.7620, lng: 3.4750 }, type: 'private_spot', pricePerHour: 60, pricePerDay: 450, pricePerWeek: 2500, pricePerMonth: 8000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1397038664/fr/photo/voitures-gar%C3%A9es-dans-un-garage-%C3%A0-plusieurs-%C3%A9tages.jpg?s=612x612&w=0&k=20&c=m2ORn2YE5KOcKvqmck8iBDcxFVJEYk71S26Fx5kJ9zI='], features: ['Centre-Ville', 'Eclairé', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'boumer-2', ownerId: 'admin', title: 'Garage - Route de Dellys', description: 'Garage sécurisé sur l\'axe coûtier vers Dellys. Entre de bonnes mains.', address: 'Route de Dellys, Boumerdès Est', location: { lat: 36.7680, lng: 3.4950 }, type: 'garage', pricePerHour: 80, pricePerDay: 600, pricePerWeek: 3500, pricePerMonth: 12000, isNegotiable: false, images: ['https://media.istockphoto.com/id/532186572/fr/photo/les-v%C3%A9hicules-dans-le-parc-de-stationnement-en-ligne.jpg?s=612x612&w=0&k=20&c=RNTuWKjX596RCWKIR7kRbWHqDW6cpbhS9D3bXF3MCS8='], features: ['Accès Plage', 'Fermé', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'boumer-3', ownerId: 'admin', title: 'Parking en Jardin - Axe Sud (Tidjelabine)', description: 'Parking privé dans un jardin sécurisé proche de l\'axe vers Alger.', address: 'Tidjelabine, Boumerdès', location: { lat: 36.7350, lng: 3.4850 }, type: 'garden_spot', pricePerHour: 50, pricePerDay: 350, pricePerWeek: 2000, pricePerMonth: 7000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1869208128/photo/a-row-of-parked-cars.jpg?s=612x612&w=0&k=20&c=6tEIF93R8KIkaCNuM0P2baAiPavFCmm6FtQ9-sED-rU='], features: ['Accès Rapide', 'Calme', 'Jardin Clos'], isAvailable: true, createdAt: Date.now() },
    { id: 'boumer-4', ownerId: 'admin', title: 'Garage Privé - Cité des 800 Logements', description: 'Garage sécurisé dans une cité résidentielle à Boumerdès.', address: 'Cité 800 Logements, Boumerdès', location: { lat: 36.7580, lng: 3.4650 }, type: 'garage', pricePerHour: 75, pricePerDay: 550, pricePerWeek: 3200, pricePerMonth: 11000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1350571198/photo/car-parked-at-parking-lot-of-the-airport-for-rental-aerial-view-of-car-parking-lot-of-the.jpg?s=612x612&w=0&k=20&c=Ty6ynDickWwoQ9scBUqXaoTdij0hQOVlkOftwNEfOKA='], features: ['Résidentiel', 'Sécurisé', 'Fermé'], isAvailable: true, createdAt: Date.now() },
    { id: 'boumer-5', ownerId: 'admin', title: 'Parking Privé - Quartier des Facultés', description: 'Parking sécurisé proche des facultés de Boumerdès.', address: 'Quartier Facultés, Boumerdès', location: { lat: 36.7650, lng: 3.4850 }, type: 'private_spot', pricePerHour: 45, pricePerDay: 350, pricePerWeek: 2000, pricePerMonth: 7000, isNegotiable: true, images: ['https://media.istockphoto.com/id/2222870577/photo/aerial-view-of-parking-lot-with-single-car.jpg?s=612x612&w=0&k=20&c=xpN9-x3VQSEO-al9LOwd52E3vEw6dV1FZQvr9Lrj4IA='], features: ['Étudiants', 'Sécurisé', 'Accessible'], isAvailable: true, createdAt: Date.now() },
    { id: 'boumer-6', ownerId: 'admin', title: 'Jardin Clos - Route de Corso', description: 'Emplacement sécurisé dans un jardin privé on the axe Boumerdès-Corso.', address: 'Route de Corso, Boumerdès', location: { lat: 36.7520, lng: 3.4450 }, type: 'garden_spot', pricePerHour: 55, pricePerDay: 400, pricePerWeek: 2200, pricePerMonth: 8000, isNegotiable: true, images: ['https://media.istockphoto.com/id/2178414859/photo/aerial-view-of-sparse-parking-lot-with-few-cars.jpg?s=612x612&w=0&k=20&c=FUAd8cXR_rwpuXjFZRqAMuA0YdEjP04fcuFZHFMQ-Go='], features: ['Jardin', 'Sécurisé', 'Axe Ouest'], isAvailable: true, createdAt: Date.now() },
    { id: 'boumer-7', ownerId: 'admin', title: 'Box Privé - Zone Industrielle Boumerdès', description: 'Box sécurisé proche de la zone industrielle de Boumerdès.', address: 'Zone Industrielle, Boumerdès', location: { lat: 36.7450, lng: 3.4950 }, type: 'garage', pricePerHour: 70, pricePerDay: 500, pricePerWeek: 3000, pricePerMonth: 10000, isNegotiable: false, images: ['https://media.istockphoto.com/id/2201862537/photo/cars-lined-up-in-a-parking-lot.jpg?s=612x612&w=0&k=20&c=M9CEct4EvUmensRC6vkyXYxyT-iQmHZkELCiJ0EpYiw='], features: ['Box', 'Sécurisé', 'Zone Calme'], isAvailable: true, createdAt: Date.now() },
    { id: 'boumer-8', ownerId: 'admin', title: 'Parking Résidentiel - Quartier Front de Mer', description: 'Parking sécurisé proche du front de mer de Boumerdès.', address: 'Front de Mer, Boumerdès', location: { lat: 36.7680, lng: 3.4780 }, type: 'private_spot', pricePerHour: 65, pricePerDay: 480, pricePerWeek: 2800, pricePerMonth: 9500, isNegotiable: true, images: ['https://images.unsplash.com/photo-1506521781263-d8422e82f27a?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'], features: ['Vue Mer', 'Sécurisé', 'Proche Plage'], isAvailable: true, createdAt: Date.now() },

    // --- BLIDA (Axes: Boulevard Mohamed Boudiaf, Route de Chréa, Axe Est) ---
    { id: 'blida-1', ownerId: 'admin', title: 'Parking Privé - Boulevard Mohamed Boudiaf', description: 'Parking très central sécurisé on the axe principal de Blida.', address: 'Boulevard Mohamed Boudiaf, Blida', location: { lat: 36.4750, lng: 2.8320 }, type: 'private_spot', pricePerHour: 70, pricePerDay: 500, pricePerWeek: 3000, pricePerMonth: 10000, isNegotiable: true, images: ['https://images.unsplash.com/photo-1526626607369-f89fe1ed77a9?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'], features: ['Centre-Ville', 'Sécurisé', 'Gardien'], isAvailable: true, createdAt: Date.now() },
    { id: 'blida-2', ownerId: 'admin', title: 'Garage - Route de Chréa', description: 'Garage fermé on the axe menant à la station de Chréa. Entre de bonnes mains.', address: 'Route de Chréa, Blida Sud', location: { lat: 36.4550, lng: 2.8450 }, type: 'garage', pricePerHour: 90, pricePerDay: 700, pricePerWeek: 4000, pricePerMonth: 14000, isNegotiable: false, images: ['https://images.unsplash.com/photo-1612917231506-a0825d1bc76d?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'], features: ['Touristique', 'Fermé', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'blida-3', ownerId: 'admin', title: 'Parking en Jardin - Axe Est (Ouled Yaich)', description: 'Parking privé dans un jardin sécurisé sur l\'axe principal vers Alger.', address: 'Ouled Yaich, Blida', location: { lat: 36.4880, lng: 2.8620 }, type: 'garden_spot', pricePerHour: 60, pricePerDay: 450, pricePerWeek: 2500, pricePerMonth: 8000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1397038664/fr/photo/voitures-gar%C3%A9es-dans-un-garage-%C3%A0-plusieurs-%C3%A9tages.jpg?s=612x612&w=0&k=20&c=m2ORn2YE5KOcKvqmck8iBDcxFVJEYk71S26Fx5kJ9zI='], features: ['Accès Rapide', 'Résidence', 'Jardin Clos'], isAvailable: true, createdAt: Date.now() },
    { id: 'blida-4', ownerId: 'admin', title: 'Garage Privé - Quartier Ben Achour', description: 'Garage sécurisé dans le quartier résidentiel de Ben Achour.', address: 'Ben Achour, Blida', location: { lat: 36.4820, lng: 2.8250 }, type: 'garage', pricePerHour: 80, pricePerDay: 600, pricePerWeek: 3500, pricePerMonth: 12000, isNegotiable: true, images: ['https://media.istockphoto.com/id/532186572/fr/photo/les-v%C3%A9hicules-dans-le-parc-de-stationnement-en-ligne.jpg?s=612x612&w=0&k=20&c=RNTuWKjX596RCWKIR7kRbWHqDW6cpbhS9D3bXF3MCS8='], features: ['Résidentiel', 'Sécurisé', 'Fermé'], isAvailable: true, createdAt: Date.now() },
    { id: 'blida-5', ownerId: 'admin', title: 'Parking Privé - Cité 1er Mai', description: 'Parking sécurisé dans la cité du 1er Mai à Blida.', address: 'Cité 1er Mai, Blida', location: { lat: 36.4650, lng: 2.8350 }, type: 'private_spot', pricePerHour: 45, pricePerDay: 350, pricePerWeek: 2000, pricePerMonth: 7000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1869208128/photo/a-row-of-parked-cars.jpg?s=612x612&w=0&k=20&c=6tEIF93R8KIkaCNuM0P2baAiPavFCmm6FtQ9-sED-rU='], features: ['Calme', 'Sécurisé', 'Accessible'], isAvailable: true, createdAt: Date.now() },
    { id: 'blida-6', ownerId: 'admin', title: 'Jardin Clos - Route de Médéa (Blida)', description: 'Emplacement sécurisé dans un jardin privé on the axe Blida-Médéa.', address: 'Route de Médéa, Blida', location: { lat: 36.4350, lng: 2.8150 }, type: 'garden_spot', pricePerHour: 55, pricePerDay: 400, pricePerWeek: 2200, pricePerMonth: 8000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1350571198/photo/car-parked-at-parking-lot-of-the-airport-for-rental-aerial-view-of-car-parking-lot-of-the.jpg?s=612x612&w=0&k=20&c=Ty6ynDickWwoQ9scBUqXaoTdij0hQOVlkOftwNEfOKA='], features: ['Jardin', 'Sécurisé', 'Axe Sud'], isAvailable: true, createdAt: Date.now() },
    { id: 'blida-7', ownerId: 'admin', title: 'Box Privé - Zone Industrielle Blida', description: 'Box sécurisé proche de la zone industrielle de Blida.', address: 'Zone Industrielle, Blida', location: { lat: 36.4950, lng: 2.8750 }, type: 'garage', pricePerHour: 70, pricePerDay: 500, pricePerWeek: 3000, pricePerMonth: 10000, isNegotiable: false, images: ['https://media.istockphoto.com/id/2222870577/photo/aerial-view-of-parking-lot-with-single-car.jpg?s=612x612&w=0&k=20&c=xpN9-x3VQSEO-al9LOwd52E3vEw6dV1FZQvr9Lrj4IA='], features: ['Box', 'Sécurisé', 'Zone Calme'], isAvailable: true, createdAt: Date.now() },
    { id: 'blida-8', ownerId: 'admin', title: 'Parking Résidentiel - Quartier Bab Dzair', description: 'Parking sécurisé dans the quartier historique de Bab Dzair.', address: 'Bab Dzair, Blida', location: { lat: 36.4780, lng: 2.8380 }, type: 'private_spot', pricePerHour: 60, pricePerDay: 450, pricePerWeek: 2500, pricePerMonth: 8500, isNegotiable: true, images: ['https://media.istockphoto.com/id/2178414859/photo/aerial-view-of-sparse-parking-lot-with-few-cars.jpg?s=612x612&w=0&k=20&c=FUAd8cXR_rwpuXjFZRqAMuA0YdEjP04fcuFZHFMQ-Go='], features: ['Historique', 'Sécurisé', 'Central'], isAvailable: true, createdAt: Date.now() },

    // --- OPTIONS PÉAGES (Autoroute Est-Ouest A1 & Est A2) ---
    // Axe Est
    { id: 'toll-alg-boum', ownerId: 'admin', title: 'Péage Alger - Boumerdes', description: 'Pass pour le tronçon Alger / Boumerdes via l\'A2. Idéal pour les navetteurs quotidiens.', address: 'Barrière de Khemis El Khechna', location: { lat: 36.6550, lng: 3.3250 }, type: 'toll_badge', pricePerHour: 20, pricePerDay: 20, pricePerWeek: 20, pricePerMonth: 20, isNegotiable: false, images: ['https://images.unsplash.com/photo-1545179212-073c880ec19d?q=80&w=1170&auto=format&fit=crop'], features: ['A2 Est', 'Navetteur', 'Voie Rapide'], isAvailable: true, createdAt: Date.now(), route: { start: { lat: 36.7525, lng: 3.0412 }, end: { lat: 36.7620, lng: 3.4750 } } },
    { id: 'toll-boum-boui', ownerId: 'admin', title: 'Péage Boumerdes - Bouira', description: 'Tronçon de montagne via Lakhdaria. Badge électronique pour passage fluide.', address: 'Gare de Péage, Lakhdaria', location: { lat: 36.5650, lng: 3.5950 }, type: 'toll_badge', pricePerHour: 20, pricePerDay: 20, pricePerWeek: 20, pricePerMonth: 20, isNegotiable: false, images: ['https://images.unsplash.com/photo-1590674899484-d3343b222275?q=80&w=1170&auto=format&fit=crop'], features: ['A1 Est', 'Axe Montagneux', 'Anti-Attente'], isAvailable: true, createdAt: Date.now(), route: { start: { lat: 36.7620, lng: 3.4750 }, end: { lat: 36.3650, lng: 3.9050 } } },
    { id: 'toll-boui-bba', ownerId: 'admin', title: 'Péage Bouira - Bordj Bou Arreridj', description: 'Traversée des Bibans. Badge recommandé pour les poids lourds et voyageurs.', address: 'Barrière de Péage, El Yachir', location: { lat: 36.0850, lng: 4.6250 }, type: 'toll_badge', pricePerHour: 20, pricePerDay: 20, pricePerWeek: 20, pricePerMonth: 20, isNegotiable: false, images: ['https://images.unsplash.com/photo-1545179212-073c880ec19d?q=80&w=1170&auto=format&fit=crop'], features: ['A1 Est', 'Bibans', 'Transit'], isAvailable: true, createdAt: Date.now(), route: { start: { lat: 36.3650, lng: 3.9050 }, end: { lat: 36.0731, lng: 4.7611 } } },
    { id: 'toll-bba-set', ownerId: 'admin', title: 'Péage BBA - Sétif', description: 'Liaison rapide entre les deux pôles économiques des Hauts Plateaux.', address: 'Barrière de Péage, Sétif Ouest', location: { lat: 36.1850, lng: 5.3250 }, type: 'toll_badge', pricePerHour: 20, pricePerDay: 20, pricePerWeek: 20, pricePerMonth: 20, isNegotiable: false, images: ['https://images.unsplash.com/photo-1590674899484-d3343b222275?q=80&w=1170&auto=format&fit=crop'], features: ['A1 Est', 'Hauts Plateaux', 'Économique'], isAvailable: true, createdAt: Date.now(), route: { start: { lat: 36.0731, lng: 4.7611 }, end: { lat: 36.1910, lng: 5.4120 } } },
    { id: 'toll-set-cons', ownerId: 'admin', title: 'Péage Sétif - Constantine', description: 'Axe majeur via El Eulma et Tadjenanet. Indispensable pour le commerce.', address: 'Gare de Péage, Constantine Ouest', location: { lat: 36.3250, lng: 6.5250 }, type: 'toll_badge', pricePerHour: 20, pricePerDay: 20, pricePerWeek: 20, pricePerMonth: 20, isNegotiable: false, images: ['https://images.unsplash.com/photo-1545179212-073c880ec19d?q=80&w=1170&auto=format&fit=crop'], features: ['A1 Est', 'Commerce', 'Voie T'], isAvailable: true, createdAt: Date.now(), route: { start: { lat: 36.1910, lng: 5.4120 }, end: { lat: 36.3650, lng: 6.6147 } } },
    { id: 'toll-cons-ann', ownerId: 'admin', title: 'Péage Constantine - Annaba', description: 'Liaison vers la côte Est et le complexe d\'El Hadjar.', address: 'Gare de Péage, Dréan', location: { lat: 36.6850, lng: 7.7250 }, type: 'toll_badge', pricePerHour: 20, pricePerDay: 20, pricePerWeek: 20, pricePerMonth: 20, isNegotiable: false, images: ['https://images.unsplash.com/photo-1590674899484-d3343b222275?q=80&w=1170&auto=format&fit=crop'], features: ['A1 Est', 'Littoral Est', 'Complexe El Hadjar'], isAvailable: true, createdAt: Date.now(), route: { start: { lat: 36.3650, lng: 6.6147 }, end: { lat: 36.9000, lng: 7.7667 } } },

    // Axe Ouest
    { id: 'toll-alg-tip', ownerId: 'admin', title: 'Péage Alger - Tipaza', description: 'Accès rapide aux plages et sites historiques via l\'autoroute de Kolea.', address: 'Barrière de Péage, Tipaza Est', location: { lat: 36.5850, lng: 2.4550 }, type: 'toll_badge', pricePerHour: 20, pricePerDay: 20, pricePerWeek: 20, pricePerMonth: 20, isNegotiable: false, images: ['https://images.unsplash.com/photo-1545179212-073c880ec19d?q=80&w=1170&auto=format&fit=crop'], features: ['A1 Ouest', 'Tourisme', 'Week-end'], isAvailable: true, createdAt: Date.now(), route: { start: { lat: 36.7525, lng: 3.0412 }, end: { lat: 36.5850, lng: 2.4550 } } },
    { id: 'toll-tip-aind', ownerId: 'admin', title: 'Péage Tipaza - Ain Defla', description: 'Passage par les gorges de Chiffa. Badge pour transit fluide.', address: 'Barrière de Péage, Khemis Miliana', location: { lat: 36.2650, lng: 2.2250 }, type: 'toll_badge', pricePerHour: 20, pricePerDay: 20, pricePerWeek: 20, pricePerMonth: 20, isNegotiable: false, images: ['https://images.unsplash.com/photo-1590674899484-d3343b222275?q=80&w=1170&auto=format&fit=crop'], features: ['A1 Ouest', 'Gorges de Chiffa', 'Passage'], isAvailable: true, createdAt: Date.now(), route: { start: { lat: 36.5850, lng: 2.4550 }, end: { lat: 36.2650, lng: 2.2250 } } },
    { id: 'toll-aind-chle', ownerId: 'admin', title: 'Péage Ain Defla - Chlef', description: 'Plaine du Chelif. Tarifs préférentiels pour les résidents locaux.', address: 'Barrière de Péage, Chlef Est', location: { lat: 36.1650, lng: 1.3350 }, type: 'toll_badge', pricePerHour: 20, pricePerDay: 20, pricePerWeek: 20, pricePerMonth: 20, isNegotiable: false, images: ['https://images.unsplash.com/photo-1545179212-073c880ec19d?q=80&w=1170&auto=format&fit=crop'], features: ['A1 Ouest', 'Plaine Chelif', 'Régional'], isAvailable: true, createdAt: Date.now(), route: { start: { lat: 36.2650, lng: 2.2250 }, end: { lat: 36.1650, lng: 1.3350 } } },
    { id: 'toll-chle-most', ownerId: 'admin', title: 'Péage Chlef - Mostaganem', description: 'Liaison vers le port et les stations balnéaires de Mostaganem.', address: 'Gare de Péage, Oued Rhiou', location: { lat: 35.9550, lng: 0.9250 }, type: 'toll_badge', pricePerHour: 20, pricePerDay: 20, pricePerWeek: 20, pricePerMonth: 20, isNegotiable: false, images: ['https://images.unsplash.com/photo-1590674899484-d3343b222275?q=80&w=1170&auto=format&fit=crop'], features: ['A1 Ouest', 'Portuaire', 'Balnéaire'], isAvailable: true, createdAt: Date.now(), route: { start: { lat: 36.1650, lng: 1.3350 }, end: { lat: 35.9550, lng: 0.9250 } } },
    { id: 'toll-most-ora', ownerId: 'admin', title: 'Péage Mostaganem - Oran', description: 'Dernière étape vers la capitale de l\'Ouest. Évitez les bouchons à l\'entrée d\'Oran.', address: 'Gare de Péage, Oran Est', location: { lat: 35.7012, lng: -0.5515 }, type: 'toll_badge', pricePerHour: 20, pricePerDay: 20, pricePerWeek: 20, pricePerMonth: 20, isNegotiable: false, images: ['https://images.unsplash.com/photo-1545179212-073c880ec19d?q=80&w=1170&auto=format&fit=crop'], features: ['A1 Ouest', 'Oran Hub', 'Prioritaire'], isAvailable: true, createdAt: Date.now(), route: { start: { lat: 35.9550, lng: 0.9250 }, end: { lat: 35.6987, lng: -0.6358 } } },

    // --- PACKS PARKING SÉTIF ---
    { id: 'park-set-mall', ownerId: 'user1', title: 'Parking Mall Sétif - Central', description: 'Emplacement premium juste en face du Park Mall. Sécurisé 24/7 avec accès direct au centre.', address: 'Cité 1014 logts, Sétif', location: { lat: 36.1911, lng: 5.4093 }, type: 'garden_spot', pricePerHour: 100, pricePerDay: 600, pricePerWeek: 3000, pricePerMonth: 10000, isNegotiable: true, images: ['https://images.unsplash.com/photo-1506521781263-d8422e82f27a?q=80&w=1170&auto=format&fit=crop'], features: ['Park Mall', 'Vidéo-surveillance', 'Accès direct'], isAvailable: true, createdAt: Date.now() },
    { id: 'park-set-university', ownerId: 'user2', title: 'Garage Université Ferhat Abbas', description: 'Idéal pour étudiants ou personnel. Garage couvert et sécurisé.', address: 'El Bez, Sétif', location: { lat: 36.1780, lng: 5.3560 }, type: 'garage', pricePerHour: 50, pricePerDay: 300, pricePerWeek: 1500, pricePerMonth: 5000, isNegotiable: false, images: ['https://images.unsplash.com/photo-1590674899484-d3343b222275?q=80&w=1170&auto=format&fit=crop'], features: ['Université', 'Couvert', 'Économique'], isAvailable: true, createdAt: Date.now() },
    { id: 'park-set-private-1', ownerId: 'user3', title: 'Parking Privé Cité 400 Logts', description: 'Parking sécurisé dans une résidence fermée à Sétif.', address: 'Cité 400 logts, Sétif', location: { lat: 36.1850, lng: 5.4200 }, type: 'private_spot', pricePerHour: 60, pricePerDay: 400, pricePerWeek: 2000, pricePerMonth: 6000, isNegotiable: true, images: ['https://images.unsplash.com/photo-1506521781263-d8422e82f27a?q=80&w=1170&auto=format&fit=crop'], features: ['Résidence', 'Calme', 'Veilleur'], isAvailable: true, createdAt: Date.now() },
    { id: 'park-set-mall-2', ownerId: 'user1', title: 'Sétif Center Mall Parking', description: 'Parking moderne avec services de lavage auto inclus. Accès facile.', address: 'Avenue de l\'ALN, Sétif', location: { lat: 36.1950, lng: 5.4150 }, type: 'garden_spot', pricePerHour: 120, pricePerDay: 700, pricePerWeek: 3500, pricePerMonth: 12000, isNegotiable: false, images: ['https://images.unsplash.com/photo-1545179212-073c880ec19d?q=80&w=1170&auto=format&fit=crop'], features: ['Lavage auto', 'Espace large', 'Toutes heures'], isAvailable: true, createdAt: Date.now() },

    // --- PACKS PARKING BOUMERDES ---
    { id: 'park-boum-beach', ownerId: 'user3', title: 'Parking Front de Mer - Boumerdes', description: 'Le meilleur spot pour vos sorties à la mer. Parking privé surveillé à 50m de la plage.', address: 'Boulevard du Front de Mer, Boumerdes', location: { lat: 36.7660, lng: 3.4730 }, type: 'private_spot', pricePerHour: 80, pricePerDay: 500, pricePerWeek: 2500, pricePerMonth: 8000, isNegotiable: true, images: ['https://images.unsplash.com/photo-1506521781263-d8422e82f27a?q=80&w=1170&auto=format&fit=crop'], features: ['Plage', 'Centre-ville', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'park-boum-station', ownerId: 'user1', title: 'Garage Gare de Boumerdes', description: 'Parfait pour les personnes prenant le train vers Alger. Accès sécurisé par badge.', address: 'Rue de la Gare, Boumerdes', location: { lat: 36.7580, lng: 3.4700 }, type: 'garage', pricePerHour: 60, pricePerDay: 400, pricePerWeek: 2000, pricePerMonth: 6500, isNegotiable: false, images: ['https://images.unsplash.com/photo-1545179212-073c880ec19d?q=80&w=1170&auto=format&fit=crop'], features: ['Gare', 'Badge', 'Pratique'], isAvailable: true, createdAt: Date.now() },
    { id: 'park-boum-mall', ownerId: 'user2', title: 'Boumerdes Mall Access', description: 'Parking souterrain du centre commercial. Très frais en été.', address: 'Centre Urbain, Boumerdes', location: { lat: 36.7610, lng: 3.4750 }, type: 'garden_spot', pricePerHour: 90, pricePerDay: 550, pricePerWeek: 2800, pricePerMonth: 9000, isNegotiable: false, images: ['https://images.unsplash.com/photo-1590674899484-d3343b222275?q=80&w=1170&auto=format&fit=crop'], features: ['Mall', 'Climatisé', 'Caméras'], isAvailable: true, createdAt: Date.now() },
    { id: 'park-boum-admin', ownerId: 'user4', title: 'Parking Privé Quartier Administratif', description: 'Idéal pour vos démarches administratives. Parking réservé.', address: 'Quartier Administratif, Boumerdes', location: { lat: 36.7630, lng: 3.4780 }, type: 'private_spot', pricePerHour: 70, pricePerDay: 450, pricePerWeek: 2200, pricePerMonth: 7500, isNegotiable: true, images: ['https://images.unsplash.com/photo-1506521781263-d8422e82f27a?q=80&w=1170&auto=format&fit=crop'], features: ['Administration', 'Rapide', 'Ombragé'], isAvailable: true, createdAt: Date.now() },
  ] as any[],
  bookings: [] as any[],
  messages: [] as any[],
};

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(cors());
  app.use(express.json());

  // --- API Routes ---

  // Auth
  app.post('/api/auth/signup', async (req, res) => {
    const { email, password, displayName, role } = req.body;
    if (db.users.find(u => u.email === email)) {
      return res.status(400).json({ error: 'Cet email est déjà utilisé.' });
    }
    const hashedPassword = await bcrypt.hash(password, 10);
    const user = { id: uuidv4(), email, password: hashedPassword, displayName, role, createdAt: Date.now() };
    db.users.push(user);
    const token = jwt.sign({ id: user.id, email: user.email, role: user.role }, JWT_SECRET);
    const { password: _, ...userWithoutPassword } = user;
    res.json({ user: userWithoutPassword, token });
  });

  app.post('/api/auth/login', async (req, res) => {
    const { email, password } = req.body;
    const user = db.users.find(u => u.email === email);
    if (!user || !(await bcrypt.compare(password, user.password))) {
      return res.status(401).json({ error: 'Identifiants invalides.' });
    }
    const token = jwt.sign({ id: user.id, email: user.email, role: user.role }, JWT_SECRET);
    const { password: _, ...userWithoutPassword } = user;
    res.json({ user: userWithoutPassword, token });
  });

  // Listings
  app.get('/api/listings', (req, res) => {
    res.json(db.listings);
  });

  app.post('/api/listings', (req, res) => {
    const listing = { ...req.body, id: uuidv4(), createdAt: Date.now() };
    db.listings.push(listing);
    res.json(listing);
  });

  // Bookings
  app.get('/api/bookings', (req, res) => {
    const { userId } = req.query;
    const userBookings = db.bookings.filter(b => b.renterId === userId || b.ownerId === userId);
    res.json(userBookings);
  });

  app.post('/api/bookings', (req, res) => {
    const booking = { ...req.body, id: uuidv4(), createdAt: Date.now(), status: 'pending' };
    db.bookings.push(booking);
    res.json(booking);
  });

  // Health
  app.get('/api/health', (req, res) => {
    res.json({ status: 'ok', users: db.users.length, listings: db.listings.length });
  });

  app.get("/api/proxy-image", async (req, res) => {
    const imageUrl = req.query.url as string;
    if (!imageUrl) return res.status(400).send("URL is required");
    try {
      const response = await fetch(imageUrl);
      const buffer = await response.arrayBuffer();
      const contentType = response.headers.get("content-type") || "image/jpeg";
      res.setHeader("Content-Type", contentType);
      res.send(Buffer.from(buffer));
    } catch (error) {
      res.status(500).send("Error fetching image");
    }
  });

  // --- Vite / Static Assets ---
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
