export const db_data = {
  users: [] as any[],
  listings: [
    // --- ALGER (Axes: Rocade Sud, Autoroute de l'Est, Boulevard des Martyrs) ---
    { id: 'alger-1', ownerId: 'admin', title: 'Garage Privé - Rocade Sud (Ben Aknoun)', description: 'Garage sécurisé à proximité immédiate de la Rocade Sud. Idéal pour éviter les bouchons. Entre de bonnes mains.', address: 'Ben Aknoun, Alger (Près Rocade Sud)', location: { lat: 36.7525, lng: 3.0185 }, type: 'garage', pricePerHour: 80, pricePerDay: 600, pricePerWeek: 3500, pricePerMonth: 12000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1397038664/fr/photo/voitures-gar%C3%A9es-dans-un-garage-%C3%A0-plusieurs-%C3%A9tages.jpg?s=612x612&w=0&k=20&c=m2ORn2YE5KOcKvqmck8iBDcxFVJEYk71S26Fx5kJ9zI='], features: ['Accès Rapide', 'Vidéosurveillance', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-2', ownerId: 'admin', title: 'Parking Privé - Autoroute de l\'Est (Bab Ezzouar)', description: 'Parking sécurisé dans une résidence clôturée, juste à côté de l\'autoroute. Surveillance 24/7.', address: 'Bab Ezzouar, Alger (Axe Autoroute Est)', location: { lat: 36.7265, lng: 3.1835 }, type: 'private_spot', pricePerHour: 60, pricePerDay: 450, pricePerWeek: 2500, pricePerMonth: 8000, isNegotiable: false, images: ['https://media.istockphoto.com/id/532186572/fr/photo/les-v%C3%A9hicules-dans-le-parc-de-stationnement-en-ligne.jpg?s=612x612&w=0&k=20&c=RNTuWKjX596RCWKIR7kRbWHqDW6cpbhS9D3bXF3MCS8='], features: ['Résidence Fermée', 'Proche Aéroport', 'Gardien'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-3', ownerId: 'admin', title: 'Parking en Jardin Sécurisé - Boulevard des Martyrs', description: 'Parking privé dans un jardin clos et sécurisé sur l\'axe principal des Martyrs. Entre de bonnes mains.', address: 'Boulevard des Martyrs, Alger Centre', location: { lat: 36.7580, lng: 3.0450 }, type: 'garden_spot', pricePerHour: 100, pricePerDay: 800, pricePerWeek: 5000, pricePerMonth: 18000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1869208128/photo/a-row-of-parked-cars.jpg?s=612x612&w=0&k=20&c=6tEIF93R8KIkaCNuM0P2baAiPavFCmm6FtQ9-sED-rU='], features: ['Jardin Clos', 'Centre-Ville', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-4', ownerId: 'admin', title: 'Garage Sécurisé - Hydra', description: 'Garage individuel fermé dans le quartier de Hydra. Très sécurisé, idéal pour longue durée.', address: 'Hydra, Alger', location: { lat: 36.7420, lng: 3.0350 }, type: 'garage', pricePerHour: 90, pricePerDay: 700, pricePerWeek: 4000, pricePerMonth: 15000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1350571198/photo/car-parked-at-parking-lot-of-the-airport-for-rental-aerial-view-of-car-parking-lot-of-the.jpg?s=612x612&w=0&k=20&c=Ty6ynDickWwoQ9scBUqXaoTdij0hQOVlkOftwNEfOKA='], features: ['Fermé', 'Quartier Chic', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-5', ownerId: 'admin', title: 'Parking Privé - Kouba', description: 'Parking dans une cour privée sécurisée à Kouba. Entre de bonnes mains.', address: 'Kouba, Alger', location: { lat: 36.7250, lng: 3.0850 }, type: 'private_spot', pricePerHour: 50, pricePerDay: 400, pricePerWeek: 2200, pricePerMonth: 7500, isNegotiable: true, images: ['https://media.istockphoto.com/id/2222870577/photo/aerial-view-of-parking-lot-with-single-car.jpg?s=612x612&w=0&k=20&c=xpN9-x3VQSEO-al9LOwd52E3vEw6dV1FZQvr9Lrj4IA='], features: ['Cour Privée', 'Calme', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-6', ownerId: 'admin', title: 'Jardin Clos - El Biar', description: 'Emplacement sécurisé dans un grand jardin à El Biar. Très discret.', address: 'El Biar, Alger', location: { lat: 36.7650, lng: 3.0280 }, type: 'garden_spot', pricePerHour: 70, pricePerDay: 550, pricePerWeek: 3000, pricePerMonth: 10000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1869208128/photo/a-row-of-parked-cars.jpg?s=612x612&w=0&k=20&c=6tEIF93R8KIkaCNuM0P2baAiPavFCmm6FtQ9-sED-rU='], features: ['Jardin', 'Discret', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-7', ownerId: 'admin', title: 'Box Privé - Cheraga', description: 'Box de stockage et parking sécurisé à Cheraga. Accès 24/7.', address: 'Cheraga, Alger', location: { lat: 36.7680, lng: 2.9550 }, type: 'garage', pricePerHour: 85, pricePerDay: 650, pricePerWeek: 3800, pricePerMonth: 13000, isNegotiable: false, images: ['https://media.istockphoto.com/id/1350571198/photo/car-parked-at-parking-lot-of-the-airport-for-rental-aerial-view-of-car-parking-lot-of-the.jpg?s=612x612&w=0&k=20&c=Ty6ynDickWwoQ9scBUqXaoTdij0hQOVlkOftwNEfOKA='], features: ['Box', 'Accès 24/7', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-8', ownerId: 'admin', title: 'Parking Résidentiel - Dely Ibrahim', description: 'Parking dans une résidence gardée à Dely Ibrahim.', address: 'Dely Ibrahim, Alger', location: { lat: 36.7520, lng: 2.9850 }, type: 'private_spot', pricePerHour: 55, pricePerDay: 420, pricePerWeek: 2400, pricePerMonth: 8500, isNegotiable: true, images: ['https://media.istockphoto.com/id/2222870577/photo/aerial-view-of-parking-lot-with-single-car.jpg?s=612x612&w=0&k=20&c=xpN9-x3VQSEO-al9LOwd52E3vEw6dV1FZQvr9Lrj4IA='], features: ['Résidence Gardée', 'Eclairé', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-sofia', ownerId: 'admin', title: 'Parking Sofia', description: 'Situé en plein centre-ville, accès facile mais parfois saturé. Idéal pour vos rendez-vous en centre-ville.', address: 'Accès Parking, Alger Centre, 16000', location: { lat: 36.77198, lng: 3.06025 }, type: 'private_spot', pricePerHour: 100, pricePerDay: 800, pricePerWeek: 4500, pricePerMonth: 15000, isNegotiable: false, images: ['https://aeroportalger.dz/assets/images/header/parking_to.jpg'], features: ['Centre-ville', 'Accès Facile', 'Surveillé'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-bouneta', ownerId: 'admin', title: 'Parking Bouneta', description: 'Parking public à Rue d’Angkor, souvent utilisé par les résidents et visiteurs. Très pratique.', address: 'Rue d’Angkor, Alger Centre', location: { lat: 36.7750, lng: 3.0580 }, type: 'private_spot', pricePerHour: 80, pricePerDay: 600, pricePerWeek: 3500, pricePerMonth: 12000, isNegotiable: true, images: ['https://www.metalstructure.dz/wp-content/uploads/2018/02/Parking2.jpg'], features: ['Résidentiel', 'Visiteurs', 'Quartier Calme'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-port', ownerId: 'admin', title: 'Parking Port d’Alger', description: 'Pratique pour les visiteurs venant en voiture depuis la côte est. Situé dans la zone du Port.', address: 'Zone du Port, Alger Centre', location: { lat: 36.7650, lng: 3.0650 }, type: 'private_spot', pricePerHour: 70, pricePerDay: 500, pricePerWeek: 3000, pricePerMonth: 10000, isNegotiable: false, images: ['https://media.istockphoto.com/id/1869208128/photo/a-row-of-parked-cars.jpg?s=612x612&w=0&k=20&c=6tEIF93R8KIkaCNuM0P2baAiPavFCmm6FtQ9-sED-rU='], features: ['Zone Portuaire', 'Accès Côte Est', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-didouche', ownerId: 'admin', title: 'Parking Didouche Mourad', description: 'Proche des commerces et du centre administratif. Emplacement stratégique sur la Rue Didouche Mourad.', address: 'Rue Didouche Mourad, Sidi M’Hamed', location: { lat: 36.7620, lng: 3.0480 }, type: 'private_spot', pricePerHour: 120, pricePerDay: 900, pricePerWeek: 5000, pricePerMonth: 18000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1350571198/photo/car-parked-at-parking-lot-of-the-airport-for-rental-aerial-view-of-car-parking-lot-of-the.jpg?s=612x612&w=0&k=20&c=Ty6ynDickWwoQ9scBUqXaoTdij0hQOVlkOftwNEfOKA='], features: ['Commerces', 'Administratif', 'Central'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-smart', ownerId: 'admin', title: 'Parking Intelligent 1er Mai', description: 'Parking moderne et surveillé à Rue Hassiba Ben Bouali. Technologie de pointe.', address: 'Rue Hassiba Ben Bouali, Sidi M’Hamed', location: { lat: 36.7520, lng: 3.0550 }, type: 'garden_spot', pricePerHour: 150, pricePerDay: 1000, pricePerWeek: 6000, pricePerMonth: 20000, isNegotiable: false, images: ['https://media.istockphoto.com/id/2222870577/photo/aerial-view-of-parking-lot-with-single-car.jpg?s=612x612&w=0&k=20&c=xpN9-x3VQSEO-al9LOwd52E3vEw6dV1FZQvr9Lrj4IA='], features: ['Moderne', 'Intelligent', 'Haute Sécurité'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-hamma', ownerId: 'admin', title: 'Parking Jardin d’Essai du Hamma', description: 'Idéal pour visiter le Jardin d’Essai ou le musée des Beaux-Arts. Très spacieux.', address: '170 Rue Hassiba Ben Bouali, Belouizdad', location: { lat: 36.7480, lng: 3.0720 }, type: 'private_spot', pricePerHour: 60, pricePerDay: 400, pricePerWeek: 2200, pricePerMonth: 8000, isNegotiable: false, images: ['https://media.istockphoto.com/id/532186572/fr/photo/les-v%C3%A9hicules-dans-le-parc-de-stationnement-en-ligne.jpg?s=612x612&w=0&k=20&c=RNTuWKjX596RCWKIR7kRbWHqDW6cpbhS9D3bXF3MCS8='], features: ['Jardin d\'Essai', 'Belouizdad', 'Spacieux'], isAvailable: true, createdAt: Date.now() },
    { id: 'alger-omar', ownerId: 'admin', title: 'Parking Omar 24/24', description: 'Pratique pour le stationnement longue durée, ouvert 24h/24 à Dar Donald.', address: 'Dar Donald, Belouizdad', location: { lat: 36.7450, lng: 3.0780 }, type: 'garage', pricePerHour: 50, pricePerDay: 350, pricePerWeek: 2000, pricePerMonth: 7000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1397038664/fr/photo/voitures-gar%C3%A9es-dans-un-garage-%C3%A0-plusieurs-%C3%A9tages.jpg?s=612x612&w=0&k=20&c=m2ORn2YE5KOcKvqmck8iBDcxFVJEYk71S26Fx5kJ9zI='], features: ['24h/24', 'Longue Durée', 'Belouizdad'], isAvailable: true, createdAt: Date.now() },

    // --- ORAN (Axes: 2ème Rocade, Boulevard Front de Mer, Route de Tlemcen) ---
    { id: 'oran-1', ownerId: 'admin', title: 'Parking Privé - 2ème Rocade (Bir El Djir)', description: 'Emplacement stratégique sur la 2ème rocade d\'Oran. Accès facile et sécurisé.', address: 'Bir El Djir, Oran (2ème Rocade)', location: { lat: 35.7280, lng: -0.5620 }, type: 'private_spot', pricePerHour: 70, pricePerDay: 500, pricePerWeek: 3000, pricePerMonth: 10000, isNegotiable: true, images: ['https://media.istockphoto.com/id/2178414859/photo/aerial-view-of-sparse-parking-lot-with-few-cars.jpg?s=612x612&w=0&k=20&c=FUAd8cXR_rwpuXjFZRqAMuA0YdEjP04fcuFZHFMQ-Go='], features: ['Accès Autoroute', 'Eclairé', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'oran-2', ownerId: 'admin', title: 'Garage - Boulevard Front de Mer', description: 'Garage privé situé sur le célèbre Front de Mer d\'Oran. Très sécurisé.', address: 'Front de Mer, Oran', location: { lat: 35.7085, lng: -0.6350 }, type: 'garage', pricePerHour: 90, pricePerDay: 700, pricePerWeek: 4000, pricePerMonth: 14000, isNegotiable: false, images: ['https://media.istockphoto.com/id/2201862537/photo/cars-lined-up-in-a-parking-lot.jpg?s=612x612&w=0&k=20&c=M9CEct4EvUmensRC6vkyXYxyT-iQmHZkELCiJ0EpYiw='], features: ['Vue Mer', 'Sécurisé', 'Fermé'], isAvailable: true, createdAt: Date.now() },
    { id: 'oran-3', ownerId: 'admin', title: 'Parking en Jardin - Route de Tlemcen', description: 'Parking calme dans un jardin privé sécurisé sur l\'axe menant à Tlemcen.', address: 'Route de Tlemcen, Oran Ouest', location: { lat: 35.6850, lng: -0.6850 }, type: 'garden_spot', pricePerHour: 50, pricePerDay: 400, pricePerWeek: 2000, pricePerMonth: 7000, isNegotiable: true, images: ['https://images.unsplash.com/photo-1506521781263-d8422e82f27a?q=80&w=1170&auto=format&fit=crop'], features: ['Calme', 'Jardin Sécurisé', 'Entre de bonnes mains'], isAvailable: true, createdAt: Date.now() },
    { id: 'oran-4', ownerId: 'admin', title: 'Garage Sécurisé - Akid Lotfi', description: 'Garage privé dans le quartier animé d\'Akid Lotfi. Sécurisé 24/7.', address: 'Akid Lotfi, Oran', location: { lat: 35.7150, lng: -0.5850 }, type: 'garage', pricePerHour: 80, pricePerDay: 600, pricePerWeek: 3500, pricePerMonth: 12000, isNegotiable: true, images: ['https://images.unsplash.com/photo-1526626607369-f89fe1ed77a9?q=80&w=1170&auto=format&fit=crop'], features: ['Fermé', 'Quartier Animé', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'oran-5', ownerId: 'admin', title: 'Parking Privé - Canastel', description: 'Parking sécurisé dans le quartier résidentiel de Canastel.', address: 'Canastel, Oran', location: { lat: 35.7350, lng: -0.5750 }, type: 'private_spot', pricePerHour: 60, pricePerDay: 450, pricePerWeek: 2500, pricePerMonth: 9000, isNegotiable: true, images: ['https://images.unsplash.com/photo-1612917231506-a0825d1bc76d?q=80&w=1170&auto=format&fit=crop'], features: ['Résidentiel', 'Calme', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'oran-6', ownerId: 'admin', title: 'Jardin Clos - Gambetta', description: 'Emplacement dans un jardin privé sécurisé à Gambetta. Entre de bonnes mains.', address: 'Gambetta, Oran', location: { lat: 35.7120, lng: -0.6150 }, type: 'garden_spot', pricePerHour: 55, pricePerDay: 400, pricePerWeek: 2200, pricePerMonth: 8000, isNegotiable: true, images: ['https://media.istockphoto.com/id/2178414859/photo/aerial-view-of-sparse-parking-lot-with-few-cars.jpg?s=612x612&w=0&k=20&c=FUAd8cXR_rwpuXjFZRqAMuA0YdEjP04fcuFZHFMQ-Go='], features: ['Jardin', 'Sécurisé', 'Proche Centre'], isAvailable: true, createdAt: Date.now() },
    { id: 'oran-7', ownerId: 'admin', title: 'Box Privé - Maraval', description: 'Box sécurisé pour voiture à Maraval. Idéal pour stationnement longue durée.', address: 'Maraval, Oran', location: { lat: 35.6880, lng: -0.6450 }, type: 'garage', pricePerHour: 75, pricePerDay: 550, pricePerWeek: 3200, pricePerMonth: 11000, isNegotiable: false, images: ['https://media.istockphoto.com/id/2201862537/photo/cars-lined-up-in-a-parking-lot.jpg?s=612x612&w=0&k=20&c=M9CEct4EvUmensRC6vkyXYxyT-iQmHZkELCiJ0EpYiw='], features: ['Box', 'Sécurisé', 'Longue Durée'], isAvailable: true, createdAt: Date.now() },
    { id: 'oran-8', ownerId: 'admin', title: 'Parking Résidentiel - Es Senia', description: 'Parking sécurisé à Es Senia, proche de l\'université.', address: 'Es Senia, Oran', location: { lat: 35.6550, lng: -0.6250 }, type: 'private_spot', pricePerHour: 45, pricePerDay: 350, pricePerWeek: 1800, pricePerMonth: 6500, isNegotiable: true, images: ['https://images.unsplash.com/photo-1506521781263-d8422e82f27a?q=80&w=1170&auto=format&fit=crop'], features: ['Proche Université', 'Sécurisé', 'Eclairé'], isAvailable: true, createdAt: Date.now() },

    // --- CONSTANTINE (Axes: Route de Batna, Route de Skikda, Centre-Ville) ---
    { id: 'const-1', ownerId: 'admin', title: 'Parking Privé - Route de Batna (Zouaghi)', description: 'Proche de l\'axe principal vers Batna et de l\'aéroport. Sécurisé.', address: 'Zouaghi Slimane, Constantine', location: { lat: 36.2980, lng: 6.6220 }, type: 'private_spot', pricePerHour: 60, pricePerDay: 450, pricePerWeek: 2500, pricePerMonth: 8000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1397038664/fr/photo/voitures-gar%C3%A9es-dans-un-garage-%C3%A0-plusieurs-%C3%A9tages.jpg?s=612x612&w=0&k=20&c=m2ORn2YE5KOcKvqmck8iBDcxFVJEYk71S26Fx5kJ9zI='], features: ['Proche Aéroport', 'Axe Principal', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'const-2', ownerId: 'admin', title: 'Garage Sécurisé - Route de Skikda', description: 'Garage fermé sur l\'axe Constantine-Skikda. Entre de bonnes mains.', address: 'Route de Skikda, Constantine Nord', location: { lat: 36.3850, lng: 6.6550 }, type: 'garage', pricePerHour: 80, pricePerDay: 600, pricePerWeek: 3500, pricePerMonth: 12000, isNegotiable: false, images: ['https://media.istockphoto.com/id/532186572/fr/photo/les-v%C3%A9hicules-dans-le-parc-de-stationnement-en-ligne.jpg?s=612x612&w=0&k=20&c=RNTuWKjX596RCWKIR7kRbWHqDW6cpbhS9D3bXF3MCS8='], features: ['Fermé', 'Vidéosurveillance', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'const-3', ownerId: 'admin', title: 'Parking en Jardin - Centre (Pont Sidi M\'Cid)', description: 'Parking privé dans un jardin à deux pas du célèbre pont suspendu. Très sécurisé.', address: 'Quartier du Pont, Constantine', location: { lat: 36.3680, lng: 6.6150 }, type: 'garden_spot', pricePerHour: 70, pricePerDay: 500, pricePerWeek: 3000, pricePerMonth: 10000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1869208128/photo/a-row-of-parked-cars.jpg?s=612x612&w=0&k=20&c=6tEIF93R8KIkaCNuM0P2baAiPavFCmm6FtQ9-sED-rU='], features: ['Vue Panoramique', 'Central', 'Jardin Clos'], isAvailable: true, createdAt: Date.now() },
    { id: 'const-4', ownerId: 'admin', title: 'Garage Privé - Nouvelle Ville (Ali Mendjeli)', description: 'Garage sécurisé dans la nouvelle ville d\'Ali Mendjeli. Accès facile.', address: 'Ali Mendjeli, Constantine', location: { lat: 36.2450, lng: 6.5850 }, type: 'garage', pricePerHour: 75, pricePerDay: 550, pricePerWeek: 3200, pricePerMonth: 11000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1350571198/photo/car-parked-at-parking-lot-of-the-airport-for-rental-aerial-view-of-car-parking-lot-of-the.jpg?s=612x612&w=0&k=20&c=Ty6ynDickWwoQ9scBUqXaoTdij0hQOVlkOftwNEfOKA='], features: ['Nouvelle Ville', 'Sécurisé', 'Fermé'], isAvailable: true, createdAt: Date.now() },
    { id: 'const-5', ownerId: 'admin', title: 'Parking Privé - Bellevue', description: 'Parking sécurisé dans le quartier calme de Bellevue.', address: 'Bellevue, Constantine', location: { lat: 36.3550, lng: 6.6050 }, type: 'private_spot', pricePerHour: 55, pricePerDay: 400, pricePerWeek: 2200, pricePerMonth: 8000, isNegotiable: true, images: ['https://media.istockphoto.com/id/2222870577/photo/aerial-view-of-parking-lot-with-single-car.jpg?s=612x612&w=0&k=20&c=xpN9-x3VQSEO-al9LOwd52E3vEw6dV1FZQvr9Lrj4IA='], features: ['Quartier Calme', 'Sécurisé', 'Eclairé'], isAvailable: true, createdAt: Date.now() },
    { id: 'const-6', ownerId: 'admin', title: 'Jardin Clos - Sidi Mabrouk', description: 'Emplacement sécurisé dans un jardin privé à Sidi Mabrouk. Entre de bonnes mains.', address: 'Sidi Mabrouk, Constantine', location: { lat: 36.3420, lng: 6.6350 }, type: 'garden_spot', pricePerHour: 50, pricePerDay: 350, pricePerWeek: 2000, pricePerMonth: 7000, isNegotiable: true, images: ['https://media.istockphoto.com/id/2178414859/photo/aerial-view-of-sparse-parking-lot-with-few-cars.jpg?s=612x612&w=0&k=20&c=FUAd8cXR_rwpuXjFZRqAMuA0YdEjP04fcuFZHFMQ-Go='], features: ['Jardin', 'Sécurisé', 'Discret'], isAvailable: true, createdAt: Date.now() },
    { id: 'const-7', ownerId: 'admin', title: 'Box Privé - El Khroub', description: 'Box sécurisé à El Khroub, idéal for stationnement longue durée.', address: 'El Khroub, Constantine', location: { lat: 36.2650, lng: 6.6950 }, type: 'garage', pricePerHour: 65, pricePerDay: 480, pricePerWeek: 2800, pricePerMonth: 9500, isNegotiable: false, images: ['https://media.istockphoto.com/id/2201862537/photo/cars-lined-up-in-a-parking-lot.jpg?s=612x612&w=0&k=20&c=M9CEct4EvUmensRC6vkyXYxyT-iQmHZkELCiJ0EpYiw='], features: ['Box', 'Sécurisé', 'Longue Durée'], isAvailable: true, createdAt: Date.now() },
    { id: 'const-8', ownerId: 'admin', title: 'Parking Résidentiel - Daksi', description: 'Parking sécurisé dans la cité Daksi. Gardiennage assuré.', address: 'Daksi, Constantine', location: { lat: 36.3580, lng: 6.6450 }, type: 'private_spot', pricePerHour: 45, pricePerDay: 350, pricePerWeek: 1800, pricePerMonth: 6000, isNegotiable: true, images: ['https://media.istockphoto.com/id/2201862537/photo/cars-lined-up-in-a-parking-lot.jpg?s=612x612&w=0&k=20&c=M9CEct4EvUmensRC6vkyXYxyT-iQmHZkELCiJ0EpYiw='], features: ['Cité Gardée', 'Sécurisé', 'Accessible'], isAvailable: true, createdAt: Date.now() },

    // --- BORDJ BOU ARRERIDJ (Axes: RN5, Autoroute Est-Ouest, Route de M\'Sila) ---
    { id: 'bba-1', ownerId: 'admin', title: 'Parking Privé - RN5 (Entrée Est)', description: 'Situé sur la route nationale 5, accès direct au centre-ville. Sécurisé.', address: 'RN5, Bordj Bou Arreridj', location: { lat: 36.0755, lng: 4.7750 }, type: 'private_spot', pricePerHour: 50, pricePerDay: 350, pricePerWeek: 2000, pricePerMonth: 7000, isNegotiable: true, images: ['https://images.unsplash.com/photo-1526626607369-f89fe1ed77a9?q=80&w=1170&auto=format&fit=crop'], features: ['Accès RN5', 'Spacieux', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'bba-2', ownerId: 'admin', title: 'Garage Fermé - Axe Autoroute (Sortie Ouest)', description: 'Garage sécurisé proche de l\'échangeur de l\'autoroute Est-Ouest. Entre de bonnes mains.', address: 'Sortie Ouest, BBA', location: { lat: 36.0650, lng: 4.7350 }, type: 'garage', pricePerHour: 70, pricePerDay: 500, pricePerWeek: 3000, pricePerMonth: 10000, isNegotiable: false, images: ['https://images.unsplash.com/photo-1612917231506-a0825d1bc76d?q=80&w=1170&auto=format&fit=crop'], features: ['Proche Autoroute', 'Sécurisé', 'Fermé'], isAvailable: true, createdAt: Date.now() },
    { id: 'bba-3', ownerId: 'admin', title: 'Parking en Jardin - Route de M\'Sila', description: 'Parking privé dans un jardin sécurisé sur l\'axe BBA-M\'Sila.', address: 'Route de M\'Sila, BBA Sud', location: { lat: 36.0550, lng: 4.7620 }, type: 'garden_spot', pricePerHour: 40, pricePerDay: 300, pricePerWeek: 1500, pricePerMonth: 5000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1397038664/fr/photo/voitures-gar%C3%A9es-dans-un-garage-%C3%A0-plusieurs-%C3%A9tages.jpg?s=612x612&w=0&k=20&c=m2ORn2YE5KOcKvqmck8iBDcxFVJEYk71S26Fx5kJ9zI='], features: ['Axe Sud', 'Calme', 'Jardin Clos'], isAvailable: true, createdAt: Date.now() },
    { id: 'bba-4', ownerId: 'admin', title: 'Garage Privé - Quartier Administratif', description: 'Garage sécurisé au centre de BBA, proche des administrations.', address: 'Centre-Ville, BBA', location: { lat: 36.0720, lng: 4.7650 }, type: 'garage', pricePerHour: 60, pricePerDay: 450, pricePerWeek: 2500, pricePerMonth: 8000, isNegotiable: true, images: ['https://media.istockphoto.com/id/532186572/fr/photo/les-v%C3%A9hicules-dans-le-parc-de-stationnement-en-ligne.jpg?s=612x612&w=0&k=20&c=RNTuWKjX596RCWKIR7kRbWHqDW6cpbhS9D3bXF3MCS8='], features: ['Central', 'Sécurisé', 'Fermé'], isAvailable: true, createdAt: Date.now() },
    { id: 'bba-5', ownerId: 'admin', title: 'Parking Privé - Cité 500 Logements', description: 'Parking sécurisé dans une cité calme à BBA.', address: 'Cité 500 Logements, BBA', location: { lat: 36.0820, lng: 4.7550 }, type: 'private_spot', pricePerHour: 35, pricePerDay: 250, pricePerWeek: 1500, pricePerMonth: 5000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1869208128/photo/a-row-of-parked-cars.jpg?s=612x612&w=0&k=20&c=6tEIF93R8KIkaCNuM0P2baAiPavFCmm6FtQ9-sED-rU='], features: ['Calme', 'Sécurisé', 'Accessible'], isAvailable: true, createdAt: Date.now() },
    { id: 'bba-6', ownerId: 'admin', title: 'Jardin Clos - Route de Sétif', description: 'Emplacement sécurisé dans un jardin privé on the axe BBA-Sétif.', address: 'Route de Sétif, BBA', location: { lat: 36.0780, lng: 4.7850 }, type: 'garden_spot', pricePerHour: 45, pricePerDay: 300, pricePerWeek: 1800, pricePerMonth: 6000, isNegotiable: true, images: ['https://media.istockphoto.com/id/1350571198/photo/car-parked-at-parking-lot-of-the-airport-for-rental-aerial-view-of-car-parking-lot-of-the.jpg?s=612x612&w=0&k=20&c=Ty6ynDickWwoQ9scBUqXaoTdij0hQOVlkOftwNEfOKA='], features: ['Jardin', 'Sécurisé', 'Axe Principal'], isAvailable: true, createdAt: Date.now() },
    { id: 'bba-7', ownerId: 'admin', title: 'Box Privé - Zone Industrielle', description: 'Box sécurisé proche de la zone industrielle de BBA.', address: 'Zone Industrielle, BBA', location: { lat: 36.0450, lng: 4.7450 }, type: 'garage', pricePerHour: 55, pricePerDay: 400, pricePerWeek: 2200, pricePerMonth: 7500, isNegotiable: false, images: ['https://media.istockphoto.com/id/2222870577/photo/aerial-view-of-parking-lot-with-single-car.jpg?s=612x612&w=0&k=20&c=xpN9-x3VQSEO-al9LOwd52E3vEw6dV1FZQvr9Lrj4IA='], features: ['Box', 'Sécurisé', 'Zone Calme'], isAvailable: true, createdAt: Date.now() },
    { id: 'bba-8', ownerId: 'admin', title: 'Parking Résidentiel - Quartier Nord', description: 'Parking sécurisé dans le quartier Nord de BBA.', address: 'Quartier Nord, BBA', location: { lat: 36.0950, lng: 4.7680 }, type: 'private_spot', pricePerHour: 30, pricePerDay: 200, pricePerWeek: 1200, pricePerMonth: 4000, isNegotiable: true, images: ['https://media.istockphoto.com/id/2178414859/photo/aerial-view-of-sparse-parking-lot-with-few-cars.jpg?s=612x612&w=0&k=20&c=FUAd8cXR_rwpuXjFZRqAMuA0YdEjP04fcuFZHFMQ-Go='], features: ['Résidentiel', 'Sécurisé', 'Economique'], isAvailable: true, createdAt: Date.now() },

    // --- SETIF (Axes: Boulevard de l\'ALN, Route de Constantine, Axe Sud) ---
    { id: 'setif-1', ownerId: 'admin', title: 'Parking Privé - Boulevard de l\'ALN', description: 'En plein coeur de Sétif, sur l\'axe principal de l\'ALN. Sécurisé.', address: 'Boulevard de l\'ALN, Sétif', location: { lat: 36.1910, lng: 5.4120 }, type: 'private_spot', pricePerHour: 60, pricePerDay: 450, pricePerWeek: 2500, pricePerMonth: 8000, isNegotiable: true, images: ['https://media.istockphoto.com/id/2201862537/photo/cars-lined-up-in-a-parking-lot.jpg?s=612x612&w=0&k=20&c=M9CEct4EvUmensRC6vkyXYxyT-iQmHZkELCiJ0EpYiw='], features: ['Centre-Ville', 'Eclairé', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },
    { id: 'setif-2', ownerId: 'admin', title: 'Garage - Route de Constantine', description: 'Garage sécurisé sur l\'axe vers Constantine. Entre de bonnes mains.', address: 'Route de Constantine, Sétif Est', location: { lat: 36.1980, lng: 5.4450 }, type: 'garage', pricePerHour: 80, pricePerDay: 600, pricePerWeek: 3500, pricePerMonth: 12000, isNegotiable: false, images: ['https://images.unsplash.com/photo-1506521781263-d8422e82f27a?q=80&w=1170&auto=format&fit=crop'], features: ['Accès Rapide', 'Fermé', 'Sécurisé'], isAvailable: true, createdAt: Date.now() },

    // --- OPTIONS PÉAGES (Autoroute Est-Ouest A1 & Est A2) ---
    { id: 'toll-alg-boum', ownerId: 'admin', title: 'Péage Alger - Boumerdes', description: 'Pass pour le tronçon Alger / Boumerdes via l\'A2. Idéal pour les navetteurs quotidiens.', address: 'Barrière de Khemis El Khechna', location: { lat: 36.6550, lng: 3.3250 }, type: 'toll_badge', pricePerHour: 20, pricePerDay: 20, pricePerWeek: 20, pricePerMonth: 20, isNegotiable: false, images: ['https://images.unsplash.com/photo-1545179212-073c880ec19d?q=80&w=1170&auto=format&fit=crop'], features: ['A2 Est', 'Navetteur', 'Voie Rapide'], isAvailable: true, createdAt: Date.now(), route: { start: { lat: 36.7525, lng: 3.0412 }, end: { lat: 36.7620, lng: 3.4750 } } },
  ],
  bookings: [] as any[],
  messages: [] as any[],
};
